import {bounds,signedArea,distance,inPolygon,overlaps} from '../geo/core.mjs';
import {validateFootprint,multi} from '../buildings/model.mjs';
import {reservationReason} from '../buildings/config.mjs';
import {area,intersection,polygons,clipped,union} from '../ground/model.mjs';
import {HERO_DEFINITIONS,HERO_CONFIG as C} from './config.mjs';
export function centroid(p){let x=0,z=0,s=0;for(const r of [p.outer,...p.holes])for(let i=0;i<r.length;i++){const a=r[i],b=r[(i+1)%r.length],q=a[0]*b[1]-b[0]*a[1];s+=q;x+=(a[0]+b[0])*q;z+=(a[1]+b[1])*q;}return [x/(3*s),z/(3*s)];}
export function edges(p){return p.outer.map((a,i)=>{const b=p.outer[(i+1)%p.outer.length],length=distance(a,b),t=[(b[0]-a[0])/length,(b[1]-a[1])/length],normal=[t[1],-t[0]];return {a,b,length,tangent:t,normal,mid:a.map((x,j)=>(x+b[j])/2),heading:Math.atan2(normal[0],normal[1]),index:i};}).filter(e=>e.length>.1);}
export function primaryFacade(p,target){const center=centroid(p),dir=target.map((v,i)=>v-center[i]),len=Math.hypot(...dir),direction=dir.map(v=>v/len);const list=edges(p).map(e=>({...e,facing:e.normal[0]*direction[0]+e.normal[1]*direction[1]}));const facing=list.filter(e=>e.facing>.7);const chosen=(facing.length?facing:list).sort((a,b)=>b.length*b.facing-a.length*a.facing)[0];return {...chosen,direction};}
export function localAxes(p){const origin=centroid(p);let best=null;for(const e of edges(p)){let u=e.tangent,v=[-u[1],u[0]];const range=axis=>{const values=p.outer.map(p=>(p[0]-origin[0])*axis[0]+(p[1]-origin[1])*axis[1]);return Math.max(...values)-Math.min(...values);};let width=range(u),depth=range(v);if(width<depth){[u,v]=[v,[-u[0],-u[1]]];[width,depth]=[depth,width];}if(u[0]<0||(Math.abs(u[0])<1e-8&&u[1]<0)){u=u.map(x=>-x);v=v.map(x=>-x);}if(!best||width*depth<best.width*best.depth-1e-6)best={origin,u,v,width,depth,heading:Math.atan2(-u[1],u[0])};}return best;}
export function auditReservations(data){const direct=data.buildings.filter(s=>reservationReason(s,data.landmarks));const rows=[];for(const source of data.buildings){const reason=reservationReason(source,data.landmarks);let parent=null;if(!reason&&!['roof','bridge'].includes(source.tags?.building))parent=direct.find(r=>overlaps(source.bounds,r.bounds)&&area(intersection(multi(source.polygon),multi(r.polygon)))>.1);if(!reason&&!parent)continue;const definition=HERO_DEFINITIONS.find(h=>h.id===source.id);const station=source.tags?.building==='train_station'||source.tags?.railway==='station'||parent?.tags?.building==='train_station';rows.push({id:source.id,key:source.id+':'+source.part,name:definition?.name??source.tags?.name??source.tags?.['name:en']??'Station structure',phase:definition?'S4':station?'S5':'other',builder:definition?.builder??null,status:definition?'pending':'untouched',reason:reason??'overlaps-reserved',parentId:parent?.id??null});}return rows;}
export function prepareHero(data,def){const source=data.buildings.find(s=>s.id===def.id);if(!source)throw Error('Missing hero source '+def.key);const v=validateFootprint(source.polygon);if(!v.ok)throw Error('Invalid hero footprint '+def.key+': '+v.reason);const sourceCentroid=centroid(v.polygon);const footprint=polygons(clipped(multi(v.polygon))).sort((a,b)=>area(multi(b))-area(multi(a)))[0];if(!footprint)throw Error('Hero outside target '+def.key);const context={...def,sourcePolygon:v.polygon,footprint,sourceCentroid,centroid:centroid(footprint),sourceBounds:v.bounds,bounds:bounds(footprint.outer),axes:{...localAxes(v.polygon),origin:centroid(footprint)},primaryFacade:primaryFacade(footprint,data.landmarks.scramble.point),height:def.height,base:C.base,masses:[],panels:[],details:[],anchors:[],placeholders:[]};return context;}
/** Intersect scaled/offset upper mass with the OSM base; never move the base footprint. */
export function setback(h,sx,sz=sx,du=0,dv=0){const {origin,u,v}=h.axes;const transform=p=>{const d=p.map((x,i)=>x-origin[i]),a=(d[0]*u[0]+d[1]*u[1])*sx+du,b=(d[0]*v[0]+d[1]*v[1])*sz+dv;return [origin[0]+a*u[0]+b*v[0],origin[1]+a*u[1]+b*v[1]];};return polygons(intersection(multi(h.footprint),multi({outer:h.footprint.outer.map(transform),holes:h.footprint.holes.map(r=>r.map(transform))}))).sort((a,b)=>area(multi(b))-area(multi(a)))[0];}
export function mass(h,label,p,bottom,top,material='concreteLight'){if(!p||top<=bottom||area(multi(p))<1)throw Error('Invalid hero mass '+label);h.masses.push({label,polygon:p,bottom:C.base+bottom,top:C.base+top,material});return p;}
export function facadePoint(e,along,y,offset=C.panelOffset){return [e.a[0]+e.tangent[0]*along+e.normal[0]*offset,C.base+y,e.a[1]+e.tangent[1]*along+e.normal[1]*offset];}
export function detail(h,e,along,y,width,height,depth,role='band',color=0xc7c9c5){h.details.push({position:facadePoint(e,along,y,.06),scale:[width,height,depth],heading:e.heading,role,color});}
export function bands(h,p,levels,{thickness=.2,color=0xc7c9c5}={}){for(const e of edges(p))if(e.length>1)for(const y of levels)detail(h,e,e.length/2,y,e.length-.1,thickness,.14,'band',color);}
export function grid(h,p,bottom,top,{pitch=3.2,floor=3.6,width=1.8,height=2.2,material='glass',skip=()=>false,mullions=false}={}){for(const e of edges(p)){const count=Math.floor((e.length-.5)/pitch);if(count<1)continue;for(let y=bottom+floor/2;y+height/2<top-.2;y+=floor)for(let i=0;i<count;i++){if(skip(e,y))continue;h.panels.push({position:facadePoint(e,(i+.5)*e.length/count,y),scale:[Math.min(width,e.length/count-.25),height,1],heading:e.heading,normal:e.normal,material,role:'window'});}if(mullions)for(let x=pitch;x<e.length-.5;x+=pitch)detail(h,e,x,(bottom+top)/2,.085,top-bottom,.11,'mullion',0xa6b2b6);}}
export function roofMass(h,p,top,{width=3,depth=2,height=1,role='mechanical'}={}){const c=centroid(p);const box=[[c[0]-width/2,c[1]-depth/2],[c[0]+width/2,c[1]-depth/2],[c[0]+width/2,c[1]+depth/2],[c[0]-width/2,c[1]+depth/2]];if(!box.every(x=>inPolygon(x,p)))return;h.details.push({position:[c[0],C.base+top+height/2,c[1]],scale:[width,height,depth],heading:0,role,color:0x929a9c});}
export function anchor(h,e,category,width,height,y,priority=1,offset=C.screenOffset){const worldPosition=facadePoint(e,e.length/2,y,offset),d=[worldPosition[0]-h.sourceCentroid[0],worldPosition[2]-h.sourceCentroid[1]];const a={id:h.key+':'+category+':'+h.anchors.length,buildingId:h.id,landmarkName:h.name,worldPosition,localPosition:[d[0]*h.axes.u[0]+d[1]*h.axes.u[1],worldPosition[1]-C.base,d[0]*h.axes.v[0]+d[1]*h.axes.v[1]],width,height,normal:[e.normal[0],0,e.normal[1]],heading:e.heading,facadeSide:'primary',category,priority,offset};h.anchors.push(a);return a;}
export function placeholder(h,e,category,width,height,y,{logicalId=null}={}){width=Math.min(width,e.length-.25);const a=anchor(h,e,category,width,height,y,category==='largeScreen'?3:1);h.panels.push({position:a.worldPosition,scale:[width,height,1],heading:e.heading,normal:e.normal,material:'screenPlaceholder',role:'placeholder',anchorId:a.id});h.placeholders.push({id:logicalId??a.id,anchorId:a.id,category});for(const sign of [-1,1]){detail(h,e,e.length/2+sign*(width/2+.09),y,.16,height+.32,.12,'screen-frame',0x30393c);detail(h,e,e.length/2,y+sign*(height/2+.09),width+.32,.16,.12,'screen-frame',0x30393c);}return a;}
export function roundFront(h){const n=h.primaryFacade.direction,t=[-n[1],n[0]],support=h.footprint.outer.reduce((best,p)=>p[0]*n[0]+p[1]*n[1]>best[0]*n[0]+best[1]*n[1]?p:best);const radius=Math.min(h.axes.width,h.axes.depth)*.17,center=support.map((x,i)=>x-n[i]*(radius+.4));const ring=Array.from({length:C.curveSegments},(_,i)=>{const a=i*Math.PI*2/C.curveSegments;return [center[0]+radius*(n[0]*Math.cos(a)+t[0]*Math.sin(a)),center[1]+radius*(n[1]*Math.cos(a)+t[1]*Math.sin(a))];});return polygons(intersection(multi(h.footprint),multi({outer:ring,holes:[]}))).sort((a,b)=>area(multi(b))-area(multi(a)))[0];}
export function footprintUnion(h){return union(...h.masses.map(m=>multi(m.polygon)));}
