export const STARTUP_TIMING_VERSION='2.0.0';

const round=value=>value==null?null:Math.max(0,Number(value.toFixed(3)));
const now=()=>performance.now();

export function createStartupTiming({initialTier,buildIdentity,browser,metrics=(_result)=>({}),clock=now}){
 const now=clock;
 const trace={instrumentationVersion:STARTUP_TIMING_VERSION,buildIdentity,browser,tier:{initial:initialTier,final:initialTier,changes:[]},milestones:{navigationStartMs:0,appLifecycleStartMs:null,rendererReadyMs:null,dataLoadStartMs:null,dataLoadCompleteMs:null,sceneBuildStartMs:null,firstRendererFrameMs:null,firstSceneFrameMs:null,sceneBuildCompleteMs:null,finalSceneFrameMs:null,interactiveReadyMs:null},stages:[],appearanceEvents:[],rebuilds:[],queueEvents:[],browserLifecycleEvents:[],totals:{navigationToSceneCompleteMs:null,navigationToInteractiveReadyMs:null,sceneBuildWallMs:null},ready:false};
 Object.defineProperty(trace,'firstMeaningfulFrameMs',{value:-1,writable:true,enumerable:false});
 const openStages=new Map(),loadStarts=new Map(),reasons=new Map(),queuedAt=new Map();
 const reasonFor=key=>{const pending=reasons.get(key);if(pending){reasons.delete(key);return pending;}return trace.milestones.interactiveReadyMs===null?'startup':'unknown';};
 const stageEndMetrics=result=>{const value=metrics(result)||{};return {triangles:value.triangles??null,drawCalls:value.drawCalls??null,objectCount:value.objectCount??null,instancedMeshCount:value.instancedMeshCount??value.instancedBatches??null,totalInstances:value.totalInstances??value.instances??null,movingVehicleCount:value.movingVehicleCount??value.moving??null,parkedVehicleCount:value.parkedVehicleCount??value.parked??null,crowdCount:value.crowdCount??value.total??null,trainCount:value.trainCount??value.sets??null};};
 function beginStage(key,name,{invocationReason,externalWaitMs=0,timing=null}={}){const at=now(),previous=[...trace.stages].reverse().find(record=>record.key===key&&record.endMs!==null),occurrence=trace.stages.filter(record=>record.key===key).length+1,record={key,name,occurrence,label:`${name} #${occurrence}`,invocationReason:invocationReason??reasonFor(key),startMs:round(at),endMs:null,wallDurationMs:null,computeMs:0,cooperativeWaitMs:0,externalWaitMs:round(externalWaitMs),unclassifiedMs:null,yieldCount:0,tierAtStart:trace.tier.final,tierAtEnd:null,sceneMetricsAtEnd:null,completedSuccessfully:false,previousBuildEndedAgoMs:previous?round(at-previous.endMs):null,timing};trace.stages.push(record);openStages.set(`${key}:${occurrence}`,record);if(trace.milestones.sceneBuildStartMs===null&&key!=='data')trace.milestones.sceneBuildStartMs=round(at);return record;}
 function endStage(record,result,completedSuccessfully=true,error=null){if(!record||record.endMs!==null)return record;const at=now(),timing=record.timing??{};record.endMs=round(at);record.wallDurationMs=round(at-record.startMs);record.computeMs=round(timing.computeMs??record.computeMs??0);record.cooperativeWaitMs=round(timing.cooperativeWaitMs??record.cooperativeWaitMs??0);record.externalWaitMs=round(timing.externalWaitMs??record.externalWaitMs??0);record.yieldCount=timing.yieldCount??record.yieldCount??0;record.unclassifiedMs=round(Math.max(0,record.wallDurationMs-record.computeMs-record.cooperativeWaitMs-record.externalWaitMs));record.tierAtEnd=trace.tier.final;record.sceneMetricsAtEnd=stageEndMetrics(result);record.completedSuccessfully=completedSuccessfully;if(error!==null)record.error=String(error);delete record.timing;openStages.delete(`${record.key}:${record.occurrence}`);if(record.occurrence>1)trace.rebuilds.push({key:record.key,name:record.name,occurrence:record.occurrence,invocationReason:record.invocationReason,tierChanged:record.tierAtStart!==record.tierAtEnd,startup:trace.milestones.interactiveReadyMs===null,previousBuildEndedAgoMs:record.previousBuildEndedAgoMs});return record;}
 function measure(key,name,run,options={}){const record=beginStage(key,name,options),started=now();try{const value=run(record);if(value&&typeof value.then==='function')return value.then(result=>{record.computeMs+=now()-started;endStage(record,result,true);return result;},error=>{record.computeMs+=now()-started;endStage(record,null,false,error);throw error;});record.computeMs+=now()-started;endStage(record,value,true);return value;}catch(error){record.computeMs+=now()-started;endStage(record,null,false,error);throw error;}}
 function loadStart(key){const token={key,startMs:now()};loadStarts.set(token,token);if(trace.milestones.dataLoadStartMs===null)trace.milestones.dataLoadStartMs=round(token.startMs);return token;}
 function loadEnd(token,successful=true,error=null){if(!token||!loadStarts.has(token)||token.endMs)return 0;token.endMs=now();token.durationMs=token.endMs-token.startMs;token.successful=successful;if(error!==null)token.error=String(error);loadStarts.delete(token);return token.durationMs;}
 function appearance(name,key){if(trace.appearanceEvents.some(event=>event.name===name))return;trace.appearanceEvents.push({name,key,atMs:round(now()),drawableOnNextFrame:true});}
 function milestone(key,at=now(),extra={}){if(trace.milestones[key]!==null&&trace.milestones[key]!==undefined)return;trace.milestones[key]=round(at);Object.assign(trace.milestones,extra);}
 function tierChange(from,to,reason){trace.tier.changes.push({from,to,changed:from!==to,reason,atMs:round(now()),startup:trace.milestones.interactiveReadyMs===null});trace.tier.final=to;}
 function setReason(key,reason){reasons.set(key,reason);}
 function queue(event){const normalized={...event,atMs:round(event.atMs),startMs:round(event.startMs),endMs:round(event.endMs),durationMs:round(event.durationMs)};if(event.type==='enqueue')queuedAt.set(event.jobId,event.atMs);if(event.type==='job-start'&&queuedAt.has(event.jobId)){const startMs=queuedAt.get(event.jobId);trace.queueEvents.push({type:'waitingForPreviousStage',jobId:event.jobId,meta:event.meta,startMs:round(startMs),endMs:round(event.atMs),durationMs:round(event.atMs-startMs),queueLength:event.queueLength,activeBuildName:event.activeBuildName,nextBuildName:event.nextBuildName});queuedAt.delete(event.jobId);}trace.queueEvents.push(normalized);}
 function browserEvent(type){trace.browserLifecycleEvents.push({type,atMs:round(now()),visibilityState:document.visibilityState,hasFocus:document.hasFocus()});}
 function completeScene(){milestone('sceneBuildCompleteMs');trace.totals.navigationToSceneCompleteMs=trace.milestones.sceneBuildCompleteMs;trace.totals.sceneBuildWallMs=round(trace.milestones.sceneBuildCompleteMs-trace.milestones.sceneBuildStartMs);}
 function finalize(){if(trace.ready)return trace;milestone('interactiveReadyMs');trace.ready=true;trace.totals.navigationToInteractiveReadyMs=trace.milestones.interactiveReadyMs;trace.tier.final=trace.tier.final;try{localStorage.setItem('shibuya.startupTiming.latest',JSON.stringify(trace));}catch{}return trace;}
 return {trace,beginStage,endStage,measure,loadStart,loadEnd,appearance,milestone,tierChange,setReason,queue,browserEvent,completeScene,finalize,get openStageCount(){return openStages.size;}};
}

export function formatStartupDuration(value){if(value==null)return 'N/A';const total=value/1000,minutes=Math.floor(total/60);return `${minutes}:${(total-minutes*60).toFixed(3).padStart(6,'0')}`;}
