import {Group,BoxGeometry,MeshStandardMaterial,InstancedMesh,Object3D,DynamicDrawUsage,InstancedBufferAttribute,BufferGeometry,Float32BufferAttribute,LineSegments,LineBasicMaterial} from 'three';
import {merge,colorize,triangleCount} from '../geo/geometry.mjs';
import {TRAIN_TYPES,buildTrainRoutes,TrainSimulation,trainPose} from './model.mjs';
function carGeometry(def){const parts=[];function box(x,y,z,w,h,d,color){const g=new BoxGeometry(w,h,d);g.translate(x,y,z);colorize(g,color);const n=g.attributes.position.count,window=color===0x294454,cap=y===1.3&&Math.abs(z)>def.length/2;g.setAttribute('s12Emission',new Float32BufferAttribute(Array.from({length:n},()=>window?[.42,.32,.18]:[0,0,0]).flat(),3));g.setAttribute('s12LampEnd',new Float32BufferAttribute(new Float32Array(n).fill(cap?Math.sign(z):0),1));parts.push(g);}
 box(0,(def.height+.55)/2,0,def.width,def.height-.55,def.length,0xc7cdd1);box(0,.4,0,def.width*.8,.8,def.length*.85,0x343e46);box(0,def.height-.12,0,def.width*.94,.24,def.length*.97,0x929ea6);
 for(const side of [-1,1]){box(side*(def.width/2+.01),1.3,0,.035,.25,def.length*.98,def.color);for(let z=-def.length/2+1.3;z<def.length/2-1;z+=2.25)box(side*(def.width/2+.025),2.3,z,.035,.8,1.45,0x294454);for(const z of [-def.length*.28,0,def.length*.28])box(side*(def.width/2+.04),1.8,z,.04,2.05,.72,0x778992);box(0,2.25,side*(def.length/2+.015),def.width*.78,.8,.03,0x294454);box(0,1.3,side*(def.length/2+.03),def.width*.9,.24,.035,def.color);}
 const g=merge(parts);parts.forEach(g=>g.dispose());return g;
}
export function buildTrains(data,{tier='medium',core=null,debug=false}={}){
 const routes=buildTrainRoutes(data,core),sim=new TrainSimulation(routes,{tier}),root=new Group();root.name='s11-background-trains';
 const material=new MeshStandardMaterial({vertexColors:true,roughness:.8});
 // This local material clips only trains; renderer/shadows/lights stay unchanged.
 material.onBeforeCompile=shader=>{shader.vertexShader='varying vec2 trainWorldXZ;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\ntrainWorldXZ = (modelMatrix * instanceMatrix * vec4(transformed, 1.0)).xz;');shader.fragmentShader='varying vec2 trainWorldXZ;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <clipping_planes_fragment>','#include <clipping_planes_fragment>\nif (max(abs(trainWorldXZ.x), abs(trainWorldXZ.y)) > 250.0) discard;');};material.customProgramCacheKey=()=> 's11-train-boundary-v1';
 const meshes={};for(const [type,def] of Object.entries(TRAIN_TYPES)){const m=new InstancedMesh(carGeometry(def),material,12);m.geometry.setAttribute('s12Cab',new InstancedBufferAttribute(new Float32Array(24),2));m.name='train-'+type;m.instanceMatrix.setUsage(DynamicDrawUsage);m.frustumCulled=false;m.count=0;meshes[type]=m;root.add(m);}
 let lines=null;if(debug){const values=[];for(const r of routes){for(let i=1;i<r.points.length;i++)values.push(r.points[i-1][0],r.railY+.1,r.points[i-1][1],r.points[i][0],r.railY+.1,r.points[i][1]);const p=trainPose(r,r.stop);values.push(p.x-2,p.y+1,p.z,p.x+2,p.y+1,p.z,p.x,p.y+1,p.z-2,p.x,p.y+1,p.z+2);}const g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(values,3));lines=new LineSegments(g,new LineBasicMaterial({color:0xffc455}));root.add(lines);}
 const obj=new Object3D(),p={},counts={JR:0,Ginza:0},stats={geometries:2,materials:1,batches:2,textures:0,lights:0,triangles:0};let disposed=false;
 function sync(){counts.JR=counts.Ginza=0;sim.forEachCar((t,i,d,def)=>{trainPose(t.route,d,p);obj.position.set(p.x,p.y,p.z);obj.rotation.set(0,p.heading,0);obj.updateMatrix();const m=meshes[t.route.type],index=counts[t.route.type]++;m.setMatrixAt(index,obj.matrix);m.geometry.attributes.s12Cab.setXY(index,i===0?-t.direction:0,i===def.cars-1?t.direction:0);});stats.triangles=0;for(const [type,m] of Object.entries(meshes)){m.count=counts[type];m.instanceMatrix.needsUpdate=true;m.geometry.attributes.s12Cab.needsUpdate=true;stats.triangles+=m.count*triangleCount(m.geometry);}Object.assign(stats,sim.snapshot(debug));}
 sync();return {root,routes,sim,stats,meshes,update(dt){if(disposed)return;sim.update(dt);sync();},setTier(t){sim.setTier(t);sync();},dispose(){if(disposed)return;disposed=true;for(const m of Object.values(meshes)){m.geometry.dispose();m.dispose();}material.dispose();lines?.geometry.dispose();lines?.material.dispose();root.removeFromParent();root.clear();}};
}
