import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {buildGroundModel}from '../src/ground/model.mjs';import {buildBuildingModel}from '../src/buildings/model.mjs';import {buildStationModel}from '../src/station/model.mjs';import {buildDetailModel}from '../src/station-detail/model.mjs';import {buildStreetscapeModel}from '../src/streetscape/model.mjs';import {buildTrafficGraph}from '../src/traffic/graph.mjs';import {TrafficSimulation}from '../src/traffic/simulation.mjs';import {buildPedestrianNetwork,route,edgePose}from '../src/life/network.mjs';import {CrowdSimulation}from '../src/life/simulation.mjs';import {buildCrowd}from '../src/life/render.mjs';import {QUALITY,ARCHETYPES,POOL_SIZE}from '../src/life/config.mjs';
const data=JSON.parse(readFileSync('public/data/shibuya-scene-data.json')),ground=buildGroundModel(data),generic=buildBuildingModel(data),core=buildStationModel(data,{ground,generic}),detail=buildDetailModel(data,{tier:'high',ground,generic,core}),street=buildStreetscapeModel(data,{tier:'high',ground,generic,core}),graph=buildTrafficGraph(data,{ground,generic,street,core}),network=buildPedestrianNetwork(data,{ground,generic,street,core,detail});
const options={ground,generic,street,core,detail,network},traffic=new TrafficSimulation(graph,{tier:'high',street}),sim=new CrowdSimulation(network,{tier:'high',traffic,choreography:true});

import {buildSignModel} from '../src/signs/model.mjs';
test('Reference cast occupies dense safe waiting bands without population growth',()=>{const a=sim.pool.filter(p=>p.active),c=a.filter(p=>p.choreographed);assert.equal(a.length,1978);assert.ok(c.length/a.length>=.8&&c.length/a.length<=.95);assert.ok(c.every(p=>Math.hypot(p.x,p.z)<80));for(const region of ['hachiko','station','center-gai'])assert.ok(a.filter(p=>!p.choreographed&&p.region===region).length>=15);assert.equal(sim.audit().major,0);writeFileSync('evidence/reference-match/allocation.json',JSON.stringify({snapshot:sim.snapshot(),cast:c.length,uniqueWaitingPositions:new Set(c.map(p=>p.x.toFixed(2)+','+p.z.toFixed(2))).size},null,2));});
test('Reference pedestrians ignore mutual occupancy but retain vehicle blocking',()=>{const p=sim.pool.find(p=>p.choreographed),q=sim.pool.find(q=>q.choreographed&&q!==p),before={x:q.x,z:q.z};q.x=p.x;q.z=p.z;sim.rebuild();assert.equal(sim.blocked(p.x,p.z,p),false);q.x=before.x;q.z=before.z;const v=traffic.pool.find(v=>v.active);assert.ok(sim.vehicleOverlap(v.x,v.z,.35));});
test('Reference full signal cycle launches simultaneous groups and restores vehicle flow',()=>{let maxCrossing=0,major=0;const samples=[];for(let f=0;f<4500;f++){traffic.update(1/30);sim.update(1/30);if(f%30===0){const a=sim.audit();major=Math.max(major,a.major);if(a.major)samples.push(...a.findings.slice(0,3));maxCrossing=Math.max(maxCrossing,sim.pool.filter(p=>p.choreographed&&p.crossing).length);if(f<2600)assert.equal(sim.pool.filter(p=>p.choreographed&&p.crossing).length,0);}}assert.equal(major,0,JSON.stringify(samples.slice(0,12)));assert.ok(maxCrossing>250);assert.equal(sim.stats.signalViolations,0);for(const e of network.crossings.filter(e=>e.kind!=='normal'))assert.ok(sim.stats.completed[e.crossingId+':'+e.direction]>0);assert.equal(traffic.signals.pedestrianOccupied('scramble'),false);assert.ok(traffic.stats.crossingEntries['scramble:NS']>0&&traffic.stats.crossingEntries['scramble:EW']>0);writeFileSync('evidence/reference-match/cycle.json',JSON.stringify({seconds:150,maxCrossing,major,snapshot:sim.snapshot(),traffic:traffic.snapshot()},null,2));});
test('Reference quality changes remain bounded and release signal occupants on disposal',()=>{traffic.signals.time=88;for(const p of sim.pool)if(p.choreographed){p.track.lastCycle=-1;p.track.cooldown=0;}for(let f=0;f<300;f++){traffic.update(1/30);sim.update(1/30);}assert.ok(sim.pool.some(p=>p.choreographed&&p.crossing));sim.setTier('low');for(let f=0;f<1500;f++){traffic.update(1/30);sim.update(1/30);}assert.equal(sim.snapshot().total,95);assert.equal(sim.audit().major,0);assert.equal(traffic.signals.pedestrianOccupied('scramble'),false);const profiles={};for(const tier of ['low','medium','high']){sim.setTier(tier);const a=sim.pool.filter(p=>p.active);assert.equal(a.length,QUALITY[tier].total);assert.ok(a.filter(p=>p.choreographed).length/a.length>=.8);profiles[tier]=sim.snapshot();}writeFileSync('evidence/reference-match/profiles.json',JSON.stringify(profiles,null,2));sim.dispose();assert.ok([...traffic.signals.pedestrians.values()].every(s=>s.size===0));traffic.dispose();});
test('Reference signage retains layer roles and valid placements with commercial concentration',()=>{const m=buildSignModel(data,{tier:'high',referenceMatch:true,ground,generic,core});assert.equal(m.audit.major,0);for(const category of ['screen','billboard','box','entrance','blade','rooftop'])assert.ok(m.signs.some(s=>s.category===category));assert.ok(m.signs.some(s=>Math.hypot(s.position[0],s.position[2])>180));writeFileSync('evidence/reference-match/signs.json',JSON.stringify(m.stats,null,2));const page=readFileSync('app/page.tsx','utf8');assert.ok(page.includes('choreography:true'));assert.ok(page.includes('referenceMatch:true'));assert.ok(page.includes('aria-expanded={!presentation}'));});
