import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {Scene,Group,Color,Mesh,PlaneGeometry,MeshStandardMaterial,HemisphereLight} from 'three';
import {TimeState} from '../src/app/foundation.mjs';import {DayNightSystem,DAY_NIGHT,installNightEmission} from '../src/environment/day-night.mjs';import {buildTrains} from '../src/trains/render.mjs';import {QUALITY} from '../src/life/config.mjs';
function fixture(){const scene=new Scene();scene.background=new Color(0x111923);const renderer={toneMappingExposure:1},time=new TimeState(),env=new DayNightSystem(scene,renderer,time);env.enable();return {scene,renderer,time,env};}
function mesh(root,name,intensity=.12){const m=new Mesh(new PlaneGeometry(),new MeshStandardMaterial({emissive:0xffffff,emissiveIntensity:intensity}));m.name=name;root.add(m);return m;}
function clean(root){root.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});root.clear();}
test('S12 one TimeState controls sky exposure sun/moon ambient and restores DAY',()=>{const {scene,renderer,time,env}=fixture(),root=new Group(),light=new HemisphereLight(0xffffff,0,2);root.add(light);scene.add(root);env.register(root);assert.equal(light.intensity,0);assert.equal(env.fill.intensity,DAY_NIGHT.day.ambient);time.set('night');assert.equal(scene.background.getHex(),DAY_NIGHT.night.sky);assert.equal(light.intensity,0);assert.equal(env.fill.intensity,DAY_NIGHT.night.ambient);assert.ok(DAY_NIGHT.day.ambient>DAY_NIGHT.night.ambient);assert.equal(renderer.toneMappingExposure,DAY_NIGHT.night.exposure);time.set('day');assert.equal(light.intensity,0);assert.equal(renderer.toneMappingExposure,DAY_NIGHT.day.exposure);assert.throws(()=>time.set('dusk'));env.dispose();assert.equal(scene.background.getHex(),0x111923);});
test('S12 existing signage and vehicle lamp materials respond without adding meshes',()=>{const {scene,time,env}=fixture(),root=new Group();scene.add(root);const signs=mesh(root,'signs-print'),front=mesh(root,'traffic-taxi-front'),rear=mesh(root,'traffic-taxi-rear',.25);env.register(root);const count=root.children.length;time.set('night');assert.equal(signs.material.emissiveIntensity,3.6);assert.equal(front.material.emissiveIntensity,6);assert.equal(rear.material.emissiveIntensity,1.65);const shader={uniforms:{},vertexShader:'#include <begin_vertex>',fragmentShader:'#include <emissivemap_fragment>'};rear.material.onBeforeCompile(shader);assert.ok(shader.fragmentShader.includes('totalEmissiveRadiance *= vColor.rgb'));assert.equal(root.children.length,count);time.set('day');assert.equal(signs.material.emissiveIntensity,.12);assert.equal(rear.material.emissiveIntensity,.25);env.dispose();clean(root);});
test('S12 windows use deterministic partial occupancy and toggle only a shared uniform',()=>{const {scene,time,env}=fixture(),root=new Group();scene.add(root);const windows=mesh(root,'buildings-windows',0);env.register(root);const shader={uniforms:{},vertexShader:'#include <begin_vertex>',fragmentShader:'#include <emissivemap_fragment>'};windows.material.onBeforeCompile(shader);const uniform=shader.uniforms.s12Night;assert.equal(uniform.value,0);assert.ok(shader.vertexShader.includes('seed<3.0'));const version=windows.material.version;time.set('night');assert.equal(uniform.value,1);time.set('day');assert.equal(uniform.value,0);assert.equal(windows.material.version,version);env.dispose();clean(root);});
test('S12 late module loads inherit NIGHT; removal and environment toggles restore owned state',()=>{const {scene,time,env}=fixture();time.set('night');const root=new Group();scene.add(root);const sign=mesh(root,'signs-led',.65);env.register(root);assert.equal(sign.material.emissiveIntensity,3.6);env.disable();assert.equal(sign.material.emissiveIntensity,.65);env.enable();assert.equal(sign.material.emissiveIntensity,3.6);root.removeFromParent();assert.equal(sign.material.emissiveIntensity,.65);assert.equal(env.roots.size,0);env.dispose();clean(root);});
test('S12 train window and end lamps preserve clipping geometry counts and movement',()=>{const data=JSON.parse(readFileSync('public/data/shibuya-scene-data.json')),r=buildTrains(data,{tier:'high'}),{scene,time,env}=fixture();scene.add(r.root);env.register(r.root);const ids=r.routes.map(x=>x.id),geometries=Object.values(r.meshes).map(m=>m.geometry);time.set('night');for(let i=0;i<250;i++)r.update(.1);const m=r.meshes.JR,shader={uniforms:{},vertexShader:'#include <begin_vertex>',fragmentShader:'#include <clipping_planes_fragment>\n#include <emissivemap_fragment>'};m.material.onBeforeCompile(shader);assert.equal(shader.uniforms.s12Night.value,1);assert.ok(shader.fragmentShader.includes('discard')&&shader.vertexShader.includes('s12Train'));assert.ok(m.geometry.attributes.s12Emission.array.some(v=>v>0));assert.ok(m.geometry.attributes.s12Cab.array.some(v=>v!==0));assert.deepEqual(r.routes.map(x=>x.id),ids);assert.deepEqual(Object.values(r.meshes).map(m=>m.geometry),geometries);assert.equal(r.stats.sets,3);env.dispose();r.dispose();});
test('S12 profiles retain crowd train and traffic source ownership; no S14 postprocess or GTA',()=>{assert.deepEqual(Object.values(QUALITY).map(p=>p.total),[1978,210,95]);const page=readFileSync('app/ShibuyaScene.tsx','utf8');assert.ok(page.includes('new DayNightSystem(scene,renderer,clock)'));for(const name of ['buildCrowd','buildTraffic','buildTrains'])assert.ok(page.includes(name));for(const name of ['buildPlayer','buildPolice','UnrealBloomPass','Reflector'])assert.ok(!page.includes(name));const {env,time}=fixture();const states={};for(const mode of ['day','night']){time.set(mode);states[mode]=env.snapshot();}mkdirSync('evidence/s12',{recursive:true});writeFileSync('evidence/s12/states.json',JSON.stringify(states,null,2));assert.equal(states.night.pointLights,0);assert.equal(states.night.shadowLights,0);env.dispose();});
