import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {Box3,Matrix4,Vector3} from 'three';
import {buildConstruction} from '../src/construction/render.mjs';import {buildBuildingModel,multi,roofFits} from '../src/buildings/model.mjs';import {buildGroundModel,intersection,area,union,buffer} from '../src/ground/model.mjs';import {TimeState,PROFILES} from '../src/app/foundation.mjs';
const data=JSON.parse(readFileSync('public/data/shibuya-scene-data.json')),generic=buildBuildingModel(data),time=new TimeState(),r=buildConstruction(data,{generic,time,tier:'high'});
const boxes=[];for(const b of r.buckets)for(let i=0;i<b.mesh.count;i++){const matrix=new Matrix4();b.mesh.getMatrixAt(i,matrix);b.geometry.computeBoundingBox();boxes.push({box:b.geometry.boundingBox.clone().applyMatrix4(matrix),part:b.parts[i]});}
mkdirSync('evidence/s15',{recursive:true});
test('S15 transforms finite and cranes/props stay on the four reserved rooftop hosts',()=>{assert.equal(r.model.zones.length,4);for(const {box,part} of boxes){assert.ok([...box.min.toArray(),...box.max.toArray()].every(Number.isFinite));const z=r.model.zones[part.zone];assert.ok(box.min.y>=z.base-1e-5);assert.ok(box.max.y<90);assert.ok(roofFits(z.roof,[(box.min.x+box.max.x)/2,(box.min.z+box.max.z)/2],box.max.x-box.min.x,box.max.z-box.min.z,0));}assert.ok(r.model.zones.every(z=>Math.hypot(...z.point)>100));});
test('S15 HIGH/MEDIUM/LOW reuse resources with bounded crane/zone counts',()=>{const identity=r.buckets.map(b=>[b.mesh.geometry,b.mesh.material,b.mesh.instanceMatrix]),states={};for(const [tier,cranes,zones] of [['high',4,4],['medium',3,3],['low',1,2]]){r.setTier(tier);assert.equal(r.stats.cranes,cranes);assert.equal(r.stats.zones,zones);const active=r.buckets.flatMap(b=>b.parts.slice(0,b.mesh.count));assert.equal(new Set(active.filter(p=>p.role==='crane').map(p=>p.zone)).size,cranes);assert.equal(new Set(active.filter(p=>p.role==='zone').map(p=>p.zone)).size,zones);assert.deepEqual(r.buckets.map(b=>[b.mesh.geometry,b.mesh.material,b.mesh.instanceMatrix]),identity);assert.ok(r.stats.drawCalls<=3);assert.ok(r.stats.triangles<7000);states[tier]={...r.stats};}assert.ok(states.high.triangles>states.medium.triangles&&states.medium.triangles>states.low.triangles);writeFileSync('evidence/s15/profiles.json',JSON.stringify(states,null,2));});
test('S15 roof-contained placement has zero road/crosswalk/rail/Hero/station interference',()=>{const ground=buildGroundModel(data),rails=union(...data.rails.map(x=>buffer(x.points,8))),heroes=union(...generic.reserved.map(b=>multi(b.polygon)));const audit={road:0,crosswalk:0,rail:0,heroStation:0,rooftopProps:0};const crossings=union(...ground.crossings.flatMap(c=>c.stripes.map(s=>s.polygon)));for(const {box,part} of boxes){const polygon=multi({outer:[[box.min.x,box.min.z],[box.max.x,box.min.z],[box.max.x,box.max.z],[box.min.x,box.max.z]],holes:[]});audit.road+=area(intersection(polygon,ground.roads));audit.crosswalk+=area(intersection(polygon,crossings));audit.rail+=area(intersection(polygon,rails));audit.heroStation+=area(intersection(polygon,heroes));const host=generic.buildings.find(b=>b.key===r.model.zones[part.zone].hostKey);for(const p of host.rooftop){const other=new Box3(new Vector3(p.center[0]-p.width/2,p.y,p.center[1]-p.depth/2),new Vector3(p.center[0]+p.width/2,p.y+p.height,p.center[1]+p.depth/2));if(box.intersectsBox(other))audit.rooftopProps++;}}for(const [key,n] of Object.entries(audit))assert.ok(n<1e-5,key+' '+n);writeFileSync('evidence/s15/placement.json',JSON.stringify({zones:r.model.zones.map(({roof,...z})=>z),audit,minimumY:Math.min(...boxes.map(b=>b.box.min.y)),navigation:'All parts contained on existing generic roofs above 36m; no ground occupancy or route edits.'},null,2));});
test('S15 warning emission changes only with shared DAY/NIGHT state; no lights/textures/animation',()=>{const marker=r.buckets.find(b=>b.name==='markers'),identity=marker.mesh;assert.equal(marker.material.emissiveIntensity,0);time.set('night');assert.equal(marker.material.emissiveIntensity,.65);time.set('day');assert.equal(marker.material.emissiveIntensity,0);assert.equal(marker.mesh,identity);assert.equal(r.update,undefined);r.root.traverse(o=>{assert.ok(!o.isLight);if(o.isMesh){assert.equal(o.castShadow,false);assert.equal(o.material.map,null);}});});
test('S15 preserves quality and scene integration without later systems or gameplay',()=>{assert.deepEqual(Object.values(PROFILES).map(p=>p.fps),[60,30,24]);const page=readFileSync('app/page.tsx','utf8');assert.ok(page.includes('constructionEntry.hooks.current?.setTier(v)'));for(const s of ['buildTraffic','buildCrowd','buildTrains','loadWetScene','frameGate.step(now)'])assert.ok(page.includes(s));for(const s of ['buildPlayer','buildPolice','buildRelease','buildVisualMatch'])assert.ok(!page.includes(s));});
test('S15 dispose is idempotent and releases pooled resources/subscription once',()=>{let count=0;const resources=new Set(r.buckets.flatMap(b=>[b.geometry,b.material,b.mesh]));for(const resource of resources)resource.addEventListener('dispose',()=>count++);r.dispose();r.dispose();assert.equal(count,resources.size);assert.equal(r.root.children.length,0);assert.equal(time.listeners.size,0);});
