import {lampGlows} from './lamp-glows.mjs';
import {addLightboxes} from './lightboxes.mjs';
import {centralDetail} from './central-detail.mjs';
import {finishStepsAsync} from '../quality/runtime.mjs';
import {Color,Group,BoxGeometry,CylinderGeometry,SphereGeometry,PlaneGeometry,MeshStandardMaterial,Mesh,CanvasTexture,DataTexture,RGBAFormat,SRGBColorSpace,LinearFilter,BufferGeometry,Float32BufferAttribute,LineSegments,LineBasicMaterial} from 'three';
import {InstancedBuilder,merge,triangleCount} from '../geo/geometry.mjs';
import {inspectGeometry} from '../ground/render.mjs';
import {buildStreetscapeModel,buildStreetscapeModelSteps} from './model.mjs';
import {installWind} from './wind.mjs';
import {regionAt} from '../signs/config.mjs';
import {QUALITY,DEFINITIONS,REGIONS} from './config.mjs';
export function createFurnitureAtlas(tier='medium',factory){const size=QUALITY[tier].atlas,canvas=factory?factory():typeof document!=='undefined'?document.createElement('canvas'):null;let texture,mode='cpu-placeholder';if(canvas){canvas.width=canvas.height=size;const c=canvas.getContext('2d');if(!c)throw Error('Furniture Canvas unavailable');for(let tile=0;tile<4;tile++){const x=tile%2*size/2,y=Math.floor(tile/2)*size/2,w=size/2;c.fillStyle=['#eaebe5','#d1444c','#203b51','#e1c07d'][tile];c.fillRect(x,y,w,w);c.fillStyle='#162a3b';c.fillRect(x+w*.08,y+w*.2,w*.84,w*.56);if(tile<2){for(let r=0;r<3;r++)for(let col=0;col<4;col++){c.fillStyle=['#81cace','#ffe7a7','#f07b74','#a6b3ed'][col];c.fillRect(x+w*(.15+col*.18),y+w*(.25+r*.15),w*.1,w*.1);}}else{c.strokeStyle='#91cbd0';c.lineWidth=w*.025;for(let i=0;i<4;i++){c.beginPath();c.moveTo(x+w*.15,y+w*(.3+i*.12));c.lineTo(x+w*.8,y+w*(.24+i*.12));c.stroke();}}c.fillStyle=tile===2?'#f4efcf':'#162a3b';c.font=`bold ${w*.09}px sans-serif`;c.textAlign='center';c.fillText(tile<2?'MIZU / DRINKS':'AREA GUIDE',x+w*.5,y+w*.13);c.font=`bold ${w*.055}px sans-serif`;c.fillText('SHIBUYA / ORIGINAL',x+w*.5,y+w*.89);}texture=new CanvasTexture(canvas);mode='canvas';}else texture=new DataTexture(new Uint8Array([230,235,220,255]),1,1,RGBAFormat);texture.colorSpace=SRGBColorSpace;texture.minFilter=texture.magFilter=LinearFilter;texture.generateMipmaps=false;texture.needsUpdate=true;return {texture,size,mode};}
export function fixtureParts(f){const parts=[],faces=[],h=f.heading,c=Math.cos(h),s=Math.sin(h),position=(x,y,z)=>[f.point[0]+c*x+s*z,f.bottom+y,f.point[1]-s*x+c*z];const add=(shape,material,x,y,z,w,height,d)=>parts.push({shape,material,position:position(x,y,z),scale:[w,height,d],heading:h,owner:f.id});
 const pole=(height,diameter=.13,material='steel',x=0,z=0)=>add('cylinder',material,x,height/2,z,diameter,height,diameter);
 switch(f.category){
 case 'lightbox':{const w=f.width,d=f.depth;if(f.entrance)add('box','cream',0,.012,1.6,w,.02,1.2);add('box','dark',0,1.5,0,w-.1,2.9,d-.1);for(const z of [-d/2+.01,d/2-.01])add('box','emissive',0,1.55,z,w-.25,2.45,.02);for(const x of [-w/2+.01,w/2-.01])add('box','emissive',x,1.55,0,.02,2.45,d-.25);add('box','dark',0,2.98,0,w,.24,d);add('box','steel',0,.12,0,w-.1,.24,d-.1);break;}
 case 'light':pole(6.25);add('box','steel',.14,6.18,0,.4,.12,.15);add('box','cream',.15,6.35,0,.4,.18,.3);add('box','emissive',.15,6.245,0,.32,.035,.24);add('sphere','emissive',.15,6.22,0,.26,.17,.26);break;
 case 'signal':pole(5.35,.17);add('box','steel',.22,4.68,0,.82,.11,.13);add('box','dark',.12,4.94,0,1.06,.4,.28);for(const x of [-.22,.12,.46]){add('sphere','lens',x,4.94,.15,.23,.23,.06);add('box','dark',x,5.11,.10,.24,.07,.14);}add('box','dark',0,2.62,0,.3,.54,.22);add('box','lens',0,2.62,.12,.21,.38,.035);break;
 case 'rail':for(const x of [-.98,.98])pole(.97,.07,'steel',x);for(const y of [.43,.9])add('box','steel',0,y,0,2.1,.055,.055);break;
 case 'bollard':pole(.76,.15);add('cylinder','cream',0,.68,0,.17,.12,.17);break;
 case 'pole':pole(7.6,.22,'cream');add('box','steel',0,7.2,0,.6,.09,.12);for(const x of [-.25,.25])add('cylinder','dark',x,7.35,0,.1,.2,.1);add('box','dark',.15,4.1,0,.2,.5,.2);break;
 case 'vending':add('box','cream',0,.925,0,1,1.85,.7);faces.push({position:position(0,.94,.358),width:.94,height:1.73,heading:h,tile:f.variation>.5?1:0});break;
 case 'box':add('box','cream',0,.625,0,.65,1.25,.5);add('box','dark',0,.76,.255,.45,.025,.01);break;
 case 'tree':{const size=.9+.1*f.variation;pole(2.8,.16,'wood');add('sphere','leaf',0,3.55,0,1.65*size,1.8*size,1.65*size);for(const [x,z] of [[-.42,.22],[.4,.27],[0,-.4]])add('sphere','leaf',x,3.1,z,1.1*size,1.4*size,1.1*size);add('box','steel',0,.04,0,1.7,.08,1.7);break;}
 case 'planter':add('box','cream',0,.22,0,1,.44,.65);add('sphere','leaf',0,.49,0,.94,.42,.58);break;
 case 'bench':for(const x of [-.55,.55])add('box','steel',x,.2,0,.09,.4,.5);add('box','wood',0,.43,0,1.5,.1,.6);add('box','wood',0,.69,-.26,1.5,.32,.1);break;
 case 'information':pole(1.8,.1);add('box','dark',0,1.45,0,.8,1.1,.2);faces.push({position:position(0,1.45,.106),width:.73,height:1,heading:h,tile:2});break;
 case 'bin':add('box','dark',0,.4,0,.45,.8,.45);add('box','cream',0,.68,.215,.3,.12,.015);break;
 default:throw Error('Unknown fixture');}
 return {parts,faces,lightAnchor:f.category==='light'?{position:position(.15,6.48,0),dayIntensity:0,nightTarget:1,emissiveReady:true}:null};
}
export function buildStreetscape(data,options={}){const started=performance.now(),model=addLightboxes(centralDetail(options.model??buildStreetscapeModel(data,options),options.stationDetail),options.stationDetail);if(model.audit.major)throw Error('Streetscape audit failed');const root=new Group();root.name='s8-streetscape';const atlas=createFurnitureAtlas(model.tier,options.canvasFactory),materials={steel:new MeshStandardMaterial({color:0x59656b,roughness:.7}),cream:new MeshStandardMaterial({color:0xd0d0c1,roughness:.8}),dark:new MeshStandardMaterial({color:0x26313a,roughness:.8}),wood:new MeshStandardMaterial({color:0x795942,roughness:.95}),leaf:new MeshStandardMaterial({color:0x496848,roughness:1}),lens:new MeshStandardMaterial({color:0x37454b,roughness:.4}),emissive:new MeshStandardMaterial({color:0xfff2d0,emissive:0xffdda2,emissiveIntensity:.2}),atlas:new MeshStandardMaterial({map:atlas.texture,emissiveMap:atlas.texture,emissive:0xffffff,emissiveIntensity:.08})};const leafDepth=installWind(materials.leaf);   // RUN 12.4: canopies sway in the wind
 const geometries={box:new BoxGeometry(1,1,1),cylinder:new CylinderGeometry(.5,.5,1,8),sphere:new SphereGeometry(.5,8,6)},builders=[],records=[],faces=[],lightAnchors=[];
 for(const f of model.fixtures){const r=fixtureParts(f);records.push(...r.parts);faces.push(...r.faces);if(r.lightAnchor)lightAnchors.push(r.lightAnchor);}
 const glare=lampGlows(lightAnchors,materials.emissive);root.add(glare.mesh);
 let triangles=lightAnchors.length*2;for(const [shape,g] of Object.entries(geometries))for(const [channel,m] of Object.entries(materials)){const list=records.filter(p=>p.shape===shape&&p.material===channel);if(!list.length)continue;const b=new InstancedBuilder(g,m,list.length);for(const p of list)b.add(...p.position,p.heading,p.scale);const mesh=b.build();mesh.name='streetscape-'+shape+'-'+channel;if(channel==='leaf')mesh.customDepthMaterial=leafDepth;root.add(mesh);builders.push(b);triangles+=triangleCount(g)*list.length;}
 const planes=faces.map(f=>{const g=new PlaneGeometry(f.width,f.height),uv=g.attributes.uv,x=f.tile%2*.5,y=Math.floor(f.tile/2)*.5,pad=4/atlas.size;for(let i=0;i<uv.count;i++)uv.setXY(i,x+pad+uv.getX(i)*(.5-2*pad),1-y-.5+pad+uv.getY(i)*(.5-2*pad));g.rotateY(f.heading);g.translate(...f.position);return g;});let faceGeometry=null;if(planes.length){faceGeometry=merge(planes);planes.forEach(g=>g.dispose());root.add(new Mesh(faceGeometry,materials.atlas));triangles+=triangleCount(faceGeometry);}
 const cablePositions=model.cables.flatMap(c=>c.points.slice(1).flatMap((p,i)=>[...c.points[i],...p]));let wire=null;if(cablePositions.length){const g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(cablePositions,3));wire=new LineSegments(g,new LineBasicMaterial({color:0x26343e}));wire.name='s8-static-cables';root.add(wire);}
 let debug=null;if(options.debug){const p=[],colors=[],palette=[0x72d4e0,0xf29c69,0x9cd57b,0xc897e2,0xf0dd73,0x729ff1,0xea81a0];let color=new Color(0xffcb6d);const add=(a,b)=>{p.push(...a,...b);colors.push(color.r,color.g,color.b,color.r,color.g,color.b);};for(const f of model.fixtures){color=new Color(palette[Object.keys(DEFINITIONS).indexOf(f.category)%palette.length]);const corners=f.polygon.outer;corners.forEach((p,i)=>add([p[0],.2,p[1]],[corners[(i+1)%4][0],.2,corners[(i+1)%4][1]]));add([f.point[0],.2,f.point[1]],[f.point[0]+f.normal[0],.2,f.point[1]+f.normal[1]]);}for(const a of model.anchors){color=new Color(palette[Object.keys(REGIONS).indexOf(regionAt(a.point))%palette.length]);add([a.point[0],.22,a.point[1]],[a.point[0],.22+REGIONS[regionAt(a.point)].density,a.point[1]]);}color=new Color(0xff4444);for(const r of model.rejected)add([r.point[0]-.2,.25,r.point[1]-.2],[r.point[0]+.2,.25,r.point[1]+.2]);const b=model.exclusion,v=[[b.minX,b.minZ],[b.maxX,b.minZ],[b.maxX,b.maxZ],[b.minX,b.maxZ]];v.forEach((p,i)=>add([p[0],.3,p[1]],[v[(i+1)%4][0],.3,v[(i+1)%4][1]]));const g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(p,3));g.setAttribute('color',new Float32BufferAttribute(colors,3));debug=new LineSegments(g,new LineBasicMaterial({vertexColors:true,depthTest:false}));debug.name='s8-fixture-clearance-rejections-exclusion';root.add(debug);}
 const stats={...model.stats,centralDetail:model.centralDetail,lightboxes:model.lightboxes??0,tier:model.tier,triangles,materials:Object.keys(materials).length+1+(wire?1:0),geometries:4+(faceGeometry?1:0)+(wire?1:0),textures:1,atlasDimensions:[atlas.size,atlas.size],atlasMode:atlas.mode,instances:records.length,batches:builders.length+1+(faceGeometry?1:0)+(wire?1:0),debugBatches:debug?1:0,pointLights:0,buildTimeMs:Math.round(performance.now()-started),checks:Object.fromEntries(Object.entries(geometries).map(([k,g])=>[k,inspectGeometry(g)]))};let disposed=false;return {root,model,stats,records,faces,lightAnchors,atlas,dispose(){if(disposed)return;disposed=true;root.removeFromParent();glare.dispose();builders.forEach(b=>b.dispose());Object.values(geometries).forEach(g=>g.dispose());Object.values(materials).forEach(m=>m.dispose());leafDepth.dispose();faceGeometry?.dispose();atlas.texture.dispose();for(const o of [wire,debug]){o?.geometry.dispose();o?.material.dispose();}root.clear();}};
}

export async function buildStreetscapeAsync(data,options={}){const timing=options.stageTiming,model=options.model??await finishStepsAsync(buildStreetscapeModelSteps(data,options),undefined,timing);const started=timing&&performance.now(),result=buildStreetscape(data,{...options,model});if(timing)timing.computeMs=(timing.computeMs??0)+(performance.now()-started);return result;}
