import {offset,length,sample,distance,SpatialIndex,bounds} from '../geo/core.mjs';
import {surface,roadWidth,buildGroundModel,polygons} from '../ground/model.mjs';
import {buildBuildingModel} from '../buildings/model.mjs';
import {DRIVEABLE,MAJOR,VEHICLES} from './config.mjs';
import {makePath,pose,connector,corners,angleDiff} from './path.mjs';
import {packContext,restoreContext} from '../quality/static-context.mjs';
const key=p=>p.map(v=>Math.round(v*100)/100).join(',');
export function pointIn(p,r){let inside=false;for(let i=0,j=r.length-1;i<r.length;j=i++){const a=r[i],b=r[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
// Every sign in the streetscape index is mounted on a building this context already holds,
// and a flush one reaches at most .3 m past that wall, so counting it as a separate roadside
// obstacle double-counts the building plus a skin. That skin is enough to delete lanes: it
// cost three of them, and with them ten transitions and more than half the crossing's
// green-phase departures. A blade reaches up to 1.1 m over the pavement and stays counted.
export function safetyContext(ground,generic,street,core){const roads=polygons(ground.roads),solid=new SpatialIndex(12);let id=0;const add=p=>solid.insert(id++,bounds(p.outer),p);for(const b of generic.buildings)add(b.polygon);for(const s of street?.fixtures??[])add(s.polygon);for(const item of street?.context?.solids?.items?.values()??[])if(item.value.bottom<3.2&&item.value.top>0&&(item.value.kind!=='sign'||item.value.overhang))add(item.value.polygon);for(const m of core?.supports??[])if(m.polygon)add(m.polygon);for(const m of core?.masses??[])if(m.bottom<3.1&&m.top>0)add(m.polygon);const onRoad=p=>roads.some(r=>pointIn(p,r.outer)&&!r.holes.some(h=>pointIn(p,h)));return {roads,solid,onRoad};}
function edgesCross(a,b,c,d){const cross=(p,q,r)=>(q[0]-p[0])*(r[1]-p[1])-(q[1]-p[1])*(r[0]-p[0]);return cross(a,b,c)*cross(a,b,d)<0&&cross(c,d,a)*cross(c,d,b)<0;}
export function safePose(ctx,p,type,padding=.15){const d=VEHICLES[type];const ring=corners(p,d.width,d.length,padding);for(let i=0;i<4;i++)if(!ctx.onRoad(ring[i])||!ctx.onRoad([(ring[i][0]+ring[(i+1)%4][0])/2,(ring[i][1]+ring[(i+1)%4][1])/2]))return false;const bb=bounds(ring);for(const {value:s} of ctx.solid.query(bb))if(ring.some(p=>pointIn(p,s.outer))||s.outer.some(p=>pointIn(p,ring))||ring.some((a,i)=>s.outer.some((c,j)=>edgesCross(a,ring[(i+1)%4],c,s.outer[(j+1)%s.outer.length]))))return false;return true;}
export function allowedOn(path,ctx,types){const p={};return types.filter(type=>{for(let d=0;d<=path.length;d+=.5)if(!safePose(ctx,pose(path,d,p),type,.3))return false;return safePose(ctx,pose(path,path.length,p),type,.3);});}
export function buildTrafficGraph(data,{ground=buildGroundModel(data),generic=buildBuildingModel(data),street=null,core=null}={}){const started=performance.now(),ctx=safetyContext(ground,generic,street,core),nodes=new Map(),edges=[],lanes=[],rejected=[];const roads=data.roads.filter(r=>surface(r)&&DRIVEABLE.has(r.highway)&&!['no','private'].includes(r.tags?.motor_vehicle??r.tags?.access));const uses=new Map();for(const r of roads)for(const p of r.points){const k=key(p);if(!uses.has(k))uses.set(k,new Set());uses.get(k).add(r.id+':'+r.part);}const node=p=>{const k=key(p);if(!nodes.has(k))nodes.set(k,{id:k,point:p,incoming:[],outgoing:[]});return nodes.get(k);};
 for(const r of roads){let start=0;for(let i=1;i<r.points.length;i++){if(i<r.points.length-1&&uses.get(key(r.points[i])).size<2)continue;const points=r.points.slice(start,i+1);start=i;if(points.some(p=>Math.abs(p[0])>249||Math.abs(p[1])>249)||length(points)<8)continue;const a=node(points[0]),b=node(points.at(-1)),one=r.oneway??r.tags?.oneway;const dirs=one==='-1'?[-1]:['yes','1','true'].includes(one)||r.tags?.junction==='roundabout'?[1]:[1,-1];const width=roadWidth(r),laneCount=Math.max(dirs.length,Math.min(6,Number(r.lanes)||Math.floor(width/3)));for(const direction of dirs){const oriented=direction===1?points:[...points].reverse(),total=length(oriented),trim=Math.min(5,total*.18),edge={id:r.id+':'+r.part+':'+i+':'+direction,sourceId:r.id,source:r,from:direction===1?a.id:b.id,to:direction===1?b.id:a.id,direction,oneway:dirs.length===1,width,roadClass:r.highway,speed:Math.min(12,(Number(r.tags?.maxspeed)|| (MAJOR.has(r.highway)?35:20))/3.6),lanes:[],points:oriented};edges.push(edge);const count=Math.max(1,Math.floor(laneCount/dirs.length));for(let index=0;index<count;index++){const shift=dirs.length===2?width/2/count*(index+.5):width/2-width/count*(index+.5);const off=offset(oriented,shift,1.6),line=[];for(let d=trim;d<total-trim;d+=2)line.push(sample(off,Math.min(d,length(off))).point);line.push(sample(off,Math.min(total-trim,length(off))).point);if(line.length<2)continue;const path=makePath(line),types=Object.keys(VEHICLES).filter(t=>!VEHICLES[t].majorOnly||(MAJOR.has(r.highway)&&width>=7));const allowed=allowedOn(path,ctx,types);if(!allowed.length){rejected.push(edge.id+':'+index);continue;}const lane={id:lanes.length,edge,index,offset:shift,path,allowed,next:[],controls:[],axis:Math.abs(pose(path,0).heading)%(Math.PI)>.78&&Math.abs(pose(path,0).heading)%(Math.PI)<2.36?'EW':'NS'};lanes.push(lane);edge.lanes.push(lane.id);nodes.get(edge.from).outgoing.push(lane.id);nodes.get(edge.to).incoming.push(lane.id);}}}}
 const transitions=[];for(const lane of lanes)for(const nextId of nodes.get(lane.edge.to).outgoing){const next=lanes[nextId];if(next.edge.to===lane.edge.from)continue;const a=pose(lane.path,lane.path.length),b=pose(next.path,0);if(Math.abs(angleDiff(b.heading,a.heading))>2.6)continue;const path=connector(lane.path,next.path);const allowed=allowedOn(path,ctx,lane.allowed.filter(t=>next.allowed.includes(t)));if(!allowed.length)continue;const t={id:transitions.length,from:lane.id,to:nextId,node:lane.edge.to,path,allowed,turn:angleDiff(b.heading,a.heading)};const ps=Array.from(path.x,(x,i)=>[x,path.z[i]]),bb=bounds(ps);t.reservationKeys=[];for(let x=Math.floor((bb.minX-5)/10);x<=Math.floor((bb.maxX+5)/10);x++)for(let z=Math.floor((bb.minZ-5)/10);z<=Math.floor((bb.maxZ+5)/10);z++)t.reservationKeys.push(x+','+z);transitions.push(t);lane.next.push(t.id);}
 return {nodes,edges,lanes,transitions,ctx,ground,data,stats:{nodes:nodes.size,edges:edges.length,lanes:lanes.length,transitions:transitions.length,rejectedLanes:rejected.length,generationMs:Math.round(performance.now()-started)}};
}

const encodeFloat64=array=>{const bytes=new Uint8Array(array.buffer,array.byteOffset,array.byteLength);let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(binary);};
const decodeFloat64=text=>{const binary=atob(text),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return new Float64Array(bytes.buffer);};
const packPath=path=>({x:encodeFloat64(path.x),z:encodeFloat64(path.z),s:encodeFloat64(path.s),h:encodeFloat64(path.h),length:path.length});
const restorePath=path=>({x:decodeFloat64(path.x),z:decodeFloat64(path.z),s:decodeFloat64(path.s),h:decodeFloat64(path.h),length:path.length});
export function packTrafficGraph(graph){
 const edgeIndex=new Map(graph.edges.map((edge,index)=>[edge,index]));
 return {nodes:[...graph.nodes],edges:graph.edges.map(({source,...edge})=>edge),lanes:graph.lanes.map(({edge,path,...lane})=>({...lane,edgeIndex:edgeIndex.get(edge),path:packPath(path)})),transitions:graph.transitions.map(({path,...transition})=>({...transition,path:packPath(path)})),ctx:packContext({roads:graph.ctx.roads,solid:graph.ctx.solid}),stats:graph.stats};
}
export function restoreTrafficGraph(model){
 const ctx=restoreContext(model.ctx);ctx.onRoad=point=>ctx.roads.some(road=>pointIn(point,road.outer)&&!road.holes.some(hole=>pointIn(point,hole)));
 const edges=model.edges,lanes=model.lanes.map(({edgeIndex,path,...lane})=>({...lane,edge:edges[edgeIndex],path:restorePath(path)}));
 return {nodes:new Map(model.nodes),edges,lanes,transitions:model.transitions.map(({path,...transition})=>({...transition,path:restorePath(path)})),ctx,ground:null,data:null,stats:model.stats};
}
