import {BufferGeometry,Float32BufferAttribute,ShapeUtils,Vector2,Shape,Path,ExtrudeGeometry,InstancedMesh,Object3D,Color,Matrix4} from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {ring,offset,cleanLine} from './core.mjs';
export function triangulate(polygon){const outer=ring(polygon.outer),holes=(polygon.holes??[]).map(ring);const vertices=[...outer,...holes.flat()];const faces=ShapeUtils.triangulateShape(outer.map(p=>new Vector2(...p)),holes.map(h=>h.map(p=>new Vector2(...p))));return {vertices,indices:faces.flat()};}
export function polygonGeometry(polygon,y=0){const {vertices,indices}=triangulate(polygon);const g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(vertices.flatMap(([x,z])=>[x,y,z]),3));g.setIndex(indices);const p=g.attributes.position,idx=g.index;for(let i=0;i<idx.count;i+=3){const a=idx.getX(i),b=idx.getX(i+1),c=idx.getX(i+2);const cross=(p.getZ(b)-p.getZ(a))*(p.getX(c)-p.getX(a))-(p.getX(b)-p.getX(a))*(p.getZ(c)-p.getZ(a));if(cross<0){idx.setX(i+1,c);idx.setX(i+2,b);}}g.computeVertexNormals();return g;}
/** Shape y=-z, rotate -PI/2 to extrude along world +Y. */
export function extrude(polygon,height,base=0){if(!Number.isFinite(height)||height<=0||!Number.isFinite(base))throw Error('Invalid extrusion height');const shape=new Shape(ring(polygon.outer).map(([x,z])=>new Vector2(x,-z)));for(const hole of polygon.holes??[])shape.holes.push(new Path(ring(hole).map(([x,z])=>new Vector2(x,-z))));const g=new ExtrudeGeometry(shape,{depth:height,bevelEnabled:false,steps:1});g.rotateX(-Math.PI/2);g.translate(0,base,0);g.computeBoundingBox();return g;}
/** Geometry utility only: not a road renderer or junction solver. */
export function ribbon(points,width,y=0){if(!Number.isFinite(width)||width<=0)throw Error('Invalid width');const p=cleanLine(points),a=offset(p,width/2),b=offset(p,-width/2),positions=[],indices=[];for(let i=0;i<p.length;i++)positions.push(a[i][0],y,a[i][1],b[i][0],y,b[i][1]);for(let i=0;i<p.length-1;i++){const j=i*2;indices.push(j,j+1,j+2,j+1,j+3,j+2);}const g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(positions,3));g.setIndex(indices);g.computeVertexNormals();return g;}
export function transform(g,matrix){if(!(matrix instanceof Matrix4))throw Error('Matrix4 required');return g.clone().applyMatrix4(matrix);}
export function colorize(g,color){const c=new Color(color),values=[];for(let i=0;i<g.attributes.position.count;i++)values.push(c.r,c.g,c.b);g.setAttribute('color',new Float32BufferAttribute(values,3));return g;}
export function triangleCount(g){return (g.index?.count??g.attributes.position.count)/3;}
export function merge(geometries){if(!geometries.length)return new BufferGeometry();const attributes=Object.keys(geometries[0].attributes).sort().join(',');if(geometries.some(g=>Object.keys(g.attributes).sort().join(',')!==attributes))throw Error('Incompatible geometry attributes');const copies=geometries.map(g=>g.index?g.toNonIndexed():g.clone());try{const result=mergeGeometries(copies,false);if(!result)throw Error('Incompatible geometry layout');result.computeBoundingBox();return result;}finally{copies.forEach(g=>g.dispose());}}
/** Prototype geometry/material remain caller-owned. */
export class InstancedBuilder{
 constructor(geometry,material,capacity=1000){if(!Number.isInteger(capacity)||capacity<1)throw Error('Invalid capacity');this.geometry=geometry;this.material=material;this.capacity=capacity;this.instances=[];this.mesh=null;}
 get count(){return this.instances.length;}
 add(x,y,z,rotation=0,scale=1,color=0xffffff,optionalRotation=null){if(this.mesh)throw Error('Builder already built');if(this.count>=this.capacity)throw Error('Instance capacity exceeded');const s=Array.isArray(scale)?scale:[scale,scale,scale];if(s.length!==3||![x,y,z,rotation,...s].every(Number.isFinite)||s.some(v=>v<=0))throw Error('Invalid instance transform');const o=new Object3D();o.position.set(x,y,z);if(optionalRotation){if(optionalRotation.length!==3||!optionalRotation.every(Number.isFinite))throw Error('Invalid Euler');o.rotation.set(...optionalRotation);}else o.rotation.y=rotation;o.scale.set(...s);o.updateMatrix();this.instances.push({matrix:o.matrix.clone(),color:new Color(color)});return this.count-1;}
 build(){if(this.mesh)return this.mesh;const mesh=new InstancedMesh(this.geometry,this.material,this.capacity);mesh.count=this.count;this.instances.forEach((v,i)=>{mesh.setMatrixAt(i,v.matrix);mesh.setColorAt(i,v.color);});mesh.instanceMatrix.needsUpdate=true;if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true;mesh.castShadow=false;mesh.receiveShadow=false;if(mesh.count){mesh.computeBoundingBox();mesh.computeBoundingSphere();}this.mesh=mesh;return mesh;}
 dispose(){this.mesh?.removeFromParent();this.mesh?.dispose();this.mesh=null;this.instances=[];}
}
