import {finishSteps} from '../quality/runtime.mjs';
import {length,sample,bounds,inPolygon,seededRandom,distance,SpatialIndex} from '../geo/core.mjs';
import {buffer,union,intersection,area,nearest,surface,buildGroundModel} from '../ground/model.mjs';
import {multi,buildBuildingModel} from '../buildings/model.mjs';
import {buildStationModel} from '../station/model.mjs';
import {DETAIL as C,DENSITY,STATION_POIS,SHOP_TYPES} from './config.mjs';
export function footprint(point,w,d,heading=0){const c=Math.cos(heading),s=Math.sin(heading);return {outer:[[-w/2,-d/2],[w/2,-d/2],[w/2,d/2],[-w/2,d/2]].map(([u,v])=>[point[0]+c*u+s*v,point[1]-s*u+c*v]),holes:[]};}
export function* buildDetailModelSteps(data,{ground=buildGroundModel(data),generic=buildBuildingModel(data),core=buildStationModel(data,{ground,generic}),tier='medium'}={}){let chunk=0;
 const started=performance.now(),density=DENSITY[tier]??DENSITY.medium,m={tier,instances:[],faces:[],fixtures:[],shops:[],wires:[],catenary:[],signals:[],rotary:[],skipped:[],collisions:[],anchors:[],baseline:{major:core.penetrations.filter(p=>p.classification==='major').length,minor:core.penetrations.filter(p=>p.classification==='minor').length},sources:{platforms:core.platforms.map(p=>p.id),railIds:core.alignments.map(a=>a.id)},atlasScope:'station-only'};
 const occupied=new SpatialIndex(10),coreIndex=new SpatialIndex(20),obstacleIndex=new SpatialIndex(25);core.masses.forEach((x,i)=>coreIndex.insert(i,x.bounds??bounds(x.polygon.outer),x));
 const obstacles=[...generic.buildings.map(b=>({id:b.id,polygon:b.polygon,top:b.height+.15})),...generic.reserved.filter(r=>!core.reservations.some(c=>c.id===r.id)).map(r=>({id:r.id,polygon:r.polygon,top:250}))];obstacles.forEach((o,i)=>obstacleIndex.insert(i,bounds(o.polygon.outer),o));
 const cross=union(...ground.crossings.flatMap(c=>c.stripes.map(s=>s.polygon))),majorFlow=union(buffer([data.landmarks.scramble.point,core.hachiko.point],4.5),...data.footways.filter(f=>surface(f)&&f.tags.highway!=='steps'&&f.points.every(p=>p[0]>-45&&p[0]<60&&p[1]>8&&p[1]<190)&&!f.tags.crossing).map(f=>buffer(f.points,Math.max(C.flowWidth,Number(f.tags.width)||0))));
 const stairShapes=core.pedestrians.filter(d=>d.stair).flatMap(d=>d.masses.map(s=>multi(s.polygon))),stairs=union(...stairShapes);
 const touch=(p,shape)=>area(intersection(multi(p),shape));
 function audit(p,bottom,top,{platform=null,groundProp=false,shop=false,coreMount=false}={}){const issues=[],bb=bounds(p.outer);
 if(p.outer.some(p=>Math.max(...p.map(Math.abs))>250))issues.push('target-boundary');
 if(obstacleIndex.query(bb).some(x=>bottom<x.value.top&&touch(p,multi(x.value.polygon))>.001))issues.push('building');
 if(core.supports.some(s=>top>s.base&&bottom<s.top&&touch(p,multi(s.polygon))>.001))issues.push('structural-pier');
 if(occupied.query(bb).some(x=>bottom<x.value.top&&top>x.value.bottom&&touch(p,multi(x.value.polygon))>.001))issues.push('other-fixture');
 if(groundProp){if(touch(p,ground.roads)>.001)issues.push('road');if(touch(p,cross)>.001)issues.push('crosswalk');if(touch(p,majorFlow)>.001)issues.push('pedestrian-flow');if(touch(p,stairs)>.001)issues.push('stairs');if(shop&&touch(p,ground.sidewalks)>.001)issues.push('storefront-sidewalk');}
 if(platform){if(!p.outer.every(q=>platform.slabs.some(s=>inPolygon(q,s.polygon))))issues.push('platform-edge');if(nearest(p.outer[0],core.alignments.filter(a=>platform.trackIds.includes(a.id)).map(a=>a.points)).distance<2)issues.push('track');for(const slab of core.masses.filter(s=>s.role==='platform-tactile'&&s.owner===platform.id))if(touch(p,multi(slab.polygon))>.001)issues.push('tactile');}
 for(const {value:s} of coreIndex.query(bb)){if(bottom>=s.top-.001||top<=s.bottom+.001)continue;if(touch(p,multi(s.polygon))<=.001)continue;if(coreMount)continue;issues.push('core:'+s.role);}
 return [...new Set(issues)];}
 function claim(role,point,w,d,bottom,top,heading=0,options={}){const polygon=footprint(point,w,d,heading),issues=audit(polygon,bottom,top,options);if(issues.length){m.skipped.push({role,point,issues});return null;}const item={id:role+':'+m.fixtures.length,role,point,width:w,depth:d,bottom,top,heading,polygon,source:options.source??null,platform:options.platform?.id??null};m.fixtures.push(item);occupied.insert(item.id,bounds(polygon.outer),item);if(options.groundProp){const a=touch(polygon,ground.sidewalks);if(a>.001)m.collisions.push({classification:'minor',category:'new-sidewalk-fixture',id:item.id,area:a,point});}return item;}
 const local=(f,x,z)=>[f.point[0]+Math.cos(f.heading)*x+Math.sin(f.heading)*z,f.point[1]-Math.sin(f.heading)*x+Math.cos(f.heading)*z];
 function box(f,role,x,y,z,w,h,d,material='metal',shape='box'){const p=local(f,x,z);m.instances.push({owner:f.id,role,position:[p[0],y,p[1]],scale:[w,h,d],heading:f.heading,material,shape});}
 function face(f,tile,x,y,z,w,h){const p=local(f,x,z);m.faces.push({owner:f.id,tile,position:[p[0],y,p[1]],width:w,height:h,heading:f.heading});}
 function beam(role,from,to,width,material='metal',owner=null){if(distance([from[0],from[2]],[to[0],to[2]])<1e-6&&Math.abs(from[1]-to[1])<1e-6)return; m.instances.push({role,owner,from,to,width,material,shape:'box'});}
 function bench(f){const y=f.bottom;box(f,'bench-seat',0,y+.48,0,1.7,.12,.48,'wood');box(f,'bench-back',0,y+.84,-.2,1.7,.55,.1,'wood');for(const x of [-.65,.65])box(f,'bench-leg',x,y+.23,0,.09,.46,.4);}
 function vending(f){const y=f.bottom;box(f,'vending-shell',0,y+.9,0,.8,1.8,.65,'cream');face(f,'vending',0,y+.94,.331,.7,1.58);box(f,'vending-slot',0,y+.27,.345,.45,.1,.025,'dark');}
 function board(f,tile,width=1.6,height=.6){const y=f.bottom;box(f,'board-shell',0,y+height/2,0,width,height,.09,'dark');face(f,tile,0,y+height/2,.051,width-.06,height-.06);}
 function platformDetails(p){const total=length(p.centers);let slot=0;for(let d=10;d<total-8;d+=density.platformPitch){const s=sample(p.centers,d),side=[s.tangent[1],-s.tangent[0]],available=Math.min(nearest(s.point,[p.edgeA]).distance,nearest(s.point,[p.edgeB]).distance),shift=Math.min(Math.max(available-1.3,0),1.4),point=s.point.map((v,i)=>v+side[i]*shift);const role=slot++%3===1?'platform-vending':'platform-bench';const f=claim(role,point,role.endsWith('bench')?1.9:1.0,.85,p.top,p.top+(role.endsWith('bench')?1.2:1.9),s.heading,{platform:p,source:p.id});if(f)(role.endsWith('bench')?bench:vending)(f);
 // Hanging signs leave the passenger/tactile plane empty and stop below roof.
 const q=sample(p.centers,Math.min(d+6,total-2)),b=claim('platform-sign',q.point,2,.16,p.roofBottom-.85,p.roofBottom-.12,q.heading,{platform:p,source:p.id});if(b){board(b,slot%2?'station':'departure',1.95,.7);for(const x of [-.7,.7])box(b,'sign-hanger',x,p.roofBottom-.05,0,.025,.1,.025);}
 const l=claim('platform-light',s.point,1.8,.15,p.roofBottom-.095,p.roofBottom-.02,s.heading,{platform:p,source:p.id});if(l)box(l,'platform-light',0,p.roofBottom-.05,0,1.8,.06,.15,'glow');
 }
 const s=sample(p.centers,total-5),cab=claim('platform-cabinet',s.point,.65,.5,p.top,p.top+1.15,s.heading,{platform:p,source:p.id});if(cab){box(cab,'cabinet',0,p.top+.55,0,.6,1.1,.45,'cream');face(cab,'wayfinding',0,p.top+.82,.231,.5,.45);}
 // A compact end safety rail stands behind tactile, never across the island.
 const q=sample(p.centers,2),f=claim('platform-safety-rail',q.point,.9,.18,p.top,p.top+1.0,q.heading,{platform:p,source:p.id});if(f){for(const x of [-.4,.4])box(f,'safety-post',x,p.top+.5,0,.04,1,.04);box(f,'safety-rail',0,p.top+.94,0,.9,.05,.05);}
 }
 for(const platform of core.platforms){platformDetails(platform);yield;}
 // Static sign band attachments have explicit S5 hosts; only face-to-host contact is allowed.
 const h=core.hachiko,hs={id:'hachiko-mounted',point:h.point,heading:h.heading};box(hs,'hachiko-sign-shell',0,4.0,.08,5,.7,.1,'green');face(hs,'station',0,4.0,.141,4.8,.6);face(hs,'clock',3.2,3.9,.13,.6,.6);m.anchors.push({type:'mounted-sign',host:h.id,position:[h.point[0],4,h.point[1]],scope:'Hachiko only'});
 for(const a of core.alignments){yield;
 if(a.family==='Ginza'){
 // OSM electrified=rail: third-rail impression, no fictitious JR overhead wires.
 for(let d=10;d<a.length-5;d+=density.polePitch){const s=sample(a.points,d),p=[s.point[0]+s.tangent[1]*1.1,s.point[1]-s.tangent[0]*1.1],f=claim('ginza-third-rail',p,.1,3,a.deckY+.24,a.deckY+.42,s.heading,{source:a.id});if(f)box(f,'third-rail-cover',0,a.deckY+.34,0,.1,.14,3,'cream');}continue;}
 const contact=a.deckY+.55+C.contactAboveRail,messenger=contact+C.messengerRise;
 for(let d=12;d<a.length-5;d+=density.polePitch){const s=sample(a.points,d),p=[s.point[0]+s.tangent[1]*C.catenaryOffset,s.point[1]-s.tangent[0]*C.catenaryOffset],f=claim('catenary-support',p,.12,.12,a.deckY,messenger+.25,s.heading,{source:a.id});if(f){box(f,'catenary-mast',0,(a.deckY+messenger+.25)/2,0,.09,messenger+.25-a.deckY,.09);beam('catenary-arm',[p[0],messenger+.1,p[1]],[s.point[0],messenger+.1,s.point[1]],.06,'metal',f.id);m.catenary.push({alignment:a.id,point:p,distance:d,bottom:a.deckY,top:messenger+.25});}}
 for(let d=0;d<a.length-.01;d+=density.wirePitch){const end=Math.min(a.length,d+density.wirePitch),u=sample(a.points,d),v=sample(a.points,end);for(const [kind,y] of [['contact-wire',contact],['messenger-wire',messenger]]){const polygon=footprint([(u.point[0]+v.point[0])/2,(u.point[1]+v.point[1])/2],.035,distance(u.point,v.point),Math.atan2(v.point[0]-u.point[0],v.point[1]-u.point[1]));const issues=audit(polygon,y-.018,y+.018);if(issues.length){m.skipped.push({role:kind,point:u.point,issues});continue;}const from=[u.point[0],y,u.point[1]],to=[v.point[0],y,v.point[1]];beam(kind,from,to,.022,'dark');m.wires.push({alignment:a.id,kind,from,to,length:Math.hypot(...from.map((v,i)=>v-to[i]))});}}
 for(let d=6;d<a.length;d+=density.dropperPitch){const s=sample(a.points,d);const p=footprint(s.point,.03,.03);if(!audit(p,contact,messenger).length)beam('dropper',[s.point[0],contact,s.point[1]],[s.point[0],messenger,s.point[1]],.018,'dark');}
 const source=data.rails.find(r=>a.sourceIds.includes(r.id)),t=source.points.at(-1).map((v,i)=>v-source.points[0][i]),ref=sample(a.points,a.length/2),travelSign=t[0]*ref.tangent[0]+t[1]*ref.tangent[1]>=0?1:-1;
 for(const fraction of [.28,.73]){const s=sample(a.points,a.length*fraction),p=[s.point[0]-s.tangent[1]*1.8,s.point[1]+s.tangent[0]*1.8],heading=s.heading+(travelSign>0?Math.PI:0),f=claim('rail-signal',p,.3,.3,a.deckY,a.deckY+2.7,heading,{source:a.id});if(f){box(f,'rail-signal-pole',0,a.deckY+1.15,0,.065,2.3,.065);box(f,'rail-signal-head',0,a.deckY+2.35,0,.23,.65,.2,'dark');box(f,'rail-signal-lens',0,a.deckY+2.5,.105,.1,.1,.025,'glow');m.signals.push({point:p,heading,travelSign,tangent:s.tangent,alignment:a.id});}}
 }
 // Selected girder-face stiffeners, a continuous cable-tray impression, guard strips.
 for(const deck of core.decks.filter(d=>d.family==='JR'))for(const side of ['left','right']){const line=deck.sections.map(s=>s[side]),total=length(line);for(let d=5;d<total;d+=density.stiffenerPitch){const s=sample(line,d),f={id:'girder-mounted',point:s.point,heading:s.heading};if(audit(footprint(s.point,.12,.12,s.heading),5.2,5.95,{coreMount:true}).length)continue;box(f,'stiffener',0,5.55,0,.1,.7,.09,'metal');if(tier==='high')for(const y of [5.35,5.7])box(f,'rivet-impression',.055,y,0,.045,.045,.045,'cream');}for(let d=0;d<total-1;d+=12){const u=sample(line,d),v=sample(line,Math.min(total,d+12));beam('cable-tray',[u.point[0],5.1,u.point[1]],[v.point[0],5.1,v.point[1]],.08,'dark');}}
 for(const p of core.supports.filter(p=>p.kind==='pier').filter((_,i)=>i%3===0)){const host=core.instances.find(i=>i.role==='pier'&&i.position&&distance([i.position[0],i.position[2]],p.point)<.001);const f={id:'pier-mounted',point:p.point,heading:host?.heading??0};for(const y of [.6,.85])box(f,'guard-stripe',0,y,.532,.85,.11,.025,'yellow');}
 const g=core.ginzaCanopy;if(g){const total=length(g.centerline);for(const end of [0,total]){const s=sample(g.centerline,end),f={id:'ginza-portal-mounted',point:s.point,heading:s.heading+(end===0?Math.PI:0)};face(f,'metro',0,g.base-.3,.3,1.0,.65);box(f,'ginza-glass-transom',0,g.base-1.15,.09,4.8,.04,.05,'metal');}
 for(const [u,rise] of g.profile.filter((_,i)=>i%2===1)){for(let d=0;d<total-.1;d+=12){const a=sample(g.centerline,d),b=sample(g.centerline,Math.min(total,d+12)),point=s=>[s.point[0]+Math.cos(s.heading)*u,g.base+rise+.03,s.point[1]-Math.sin(s.heading)*u];beam('ginza-roof-seam',point(a),point(b),.035,'metal','ginza-roof-mounted');}}
 }
 function groundCandidate(role,anchor,w,d,h,{heading=0,radius=6,source=null,shop=false}={}){for(const delta of [[0,0],...[2,4,6].filter(v=>v<=radius).flatMap(r=>[[r,0],[-r,0],[0,r],[0,-r],[r*.7,r*.7],[-r*.7,r*.7]])]){const p=[anchor[0]+delta[0],anchor[1]+delta[1]];if(p[0]<C.scope.minX||p[0]>C.scope.maxX||p[1]<C.scope.minZ||p[1]>C.scope.maxZ)continue;const polygon=footprint(p,w,d,heading);if(role.endsWith('shelter')&&touch(polygon,ground.sidewalks)>2){m.skipped.push({role,point:p,issues:['shelter-sidewalk-clearance']});continue;}const base=touch(polygon,ground.sidewalks)>.001?(ground.height?.(p)??.15):0;const f=claim(role,p,w,d,base,base+h,heading,{groundProp:true,shop,source});if(f)return f;}return null;}
 function shelter(f,type){const y=f.bottom;for(const x of [-2.1,2.1])box(f,'shelter-post',x,y+1.3,-.55,.12,2.6,.12);box(f,'shelter-roof',0,y+2.65,0,4.8,.15,1.8,'cream');box(f,'shelter-back',0,y+1.3,-.69,4.4,2,.05,'glass');face(f,type,0,y+2.4,.72,2.1,.35);box(f,'shelter-seat',0,y+.55,-.3,2.8,.13,.42,'wood');m.rotary.push({type:type+'-shelter',id:f.id,point:f.point,polygon:f.polygon,source:f.source});}
 for(const id of STATION_POIS.bus){const source=data.pois.find(p=>p.id===id);if(!source)continue;const f=groundCandidate('bus-shelter',source.point,5,2,2.8,{source:id,radius:6});if(f)shelter(f,'bus');}
 const taxi=groundCandidate('taxi-shelter',STATION_POIS.taxiComposition,5,2,2.8,{radius:6,source:'POC composition inside west rotary; no mapped taxi POI'});if(taxi)shelter(taxi,'taxi');
 for(const [key,tile] of [['koban','police'],['info','kiosk']]){const source=data.pois.find(p=>p.id===STATION_POIS[key]);if(!source)continue;const f=groundCandidate(key,source.point,key==='koban'?2.8:1.4,key==='koban'?2:1,3,{source:source.id,radius:key==='koban'?0:4});if(!f)continue;const y=f.bottom;box(f,key+'-mass',0,y+1.25,0,f.width-.15,2.5,f.depth-.15,'cream');box(f,key+'-roof',0,y+2.7,0,f.width,.15,f.depth,'dark');box(f,key+'-window',0,y+1.6,f.depth/2-.055,f.width*.6,.7,.05,'glass');face(f,tile,0,y+2.35,f.depth/2+.01,f.width*.85,.45);m.rotary.push({type:key,id:f.id,point:f.point,polygon:f.polygon,source:source.id});}
 // Curated station-front edge candidates only; no citywide furniture placement.
 for(const [i,p] of [[20,55],[30,65],[22,78],[32,95],[40,148],[35,165],[40,180],[18,142],[8,165],[-23,52],[-20,65]].entries()){const type=['globe-lamp','plaza-bench','map-board','planter'][i%4],f=groundCandidate(type,p,type==='plaza-bench'?1.9:type==='planter'?1.4:.55,type==='plaza-bench'?.8:type==='planter'?1.4:.55,type==='globe-lamp'?3.3:type==='map-board'?2.2:1.25,{radius:4,source:'station-front composition candidate'});if(!f)continue;const y=f.bottom;if(type==='plaza-bench')bench(f);else if(type==='globe-lamp'){box(f,'globe-pole',0,y+1.5,0,.08,3,.08);box(f,'globe-lamp',0,y+3.07,0,.38,.38,.38,'glow','sphere');}else if(type==='planter'){box(f,'planter',0,y+.22,0,1.3,.44,1.3,'cream');box(f,'bush',0,y+.65,0,1.2,.7,1.2,'green','sphere');}else{box(f,'map-post',0,y+.85,0,.08,1.7,.08);const b={...f,bottom:y+1.2};board(b,'map',.5,.85);}m.rotary.push({type,id:f.id,point:f.point,polygon:f.polygon});}
 // Recessed vignettes lie inside the JR deck envelope between structural supports.
 const jrDeck=core.decks.find(d=>d.family==='JR'),edge=jrDeck.sections.map(s=>s.left),rng=seededRandom(C.seed);let shopIndex=0;
 for(let d=length(edge)*.60;d<length(edge)*.9&&shopIndex<8;d+=8){const s=sample(edge,d),point=[s.point[0]+2.1,s.point[1]],heading=s.heading-Math.PI/2,polygon=footprint(point,5.2,3,heading);if(!polygon.outer.every(p=>jrDeck.masses.some(x=>inPolygon(p,x.polygon))))continue;const f=groundCandidate('gadoshita',point,5.2,3,3.9,{heading,radius:0,shop:true,source:'JR deck west edge; procedural not actual storefront'});if(!f)continue;const type=SHOP_TYPES[shopIndex++%SHOP_TYPES.length],variation=rng(),y=f.bottom;box(f,'shop-rear',0,y+1.75,-1.3,5,3.5,.18,'wood');for(const x of [-2.4,2.4])box(f,'shop-side',x,y+1.75,0,.16,3.5,2.6,'dark');box(f,'shop-ceiling',0,y+3.55,0,5,.13,2.7,'dark');box(f,'fascia',0,y+3.05,1.25,4.8,.55,.15,type==='convenience'?'green':'wood');face(f,type==='shutter'?'menu':type,0,y+3.05,1.34,4.4,.43);
 if(type==='shutter'){box(f,'shutter',0,y+1.45,1.12,4.55,2.6,.08,'metal');for(let yy=.4;yy<2.7;yy+=.25)box(f,'shutter-slat',0,y+yy,1.17,4.55,.025,.025,'dark');}else{box(f,'shop-door',-.9,y+1.35,.88,1.1,2.5,.08,'glass');box(f,'shop-window',.95,y+1.7,.88,1.8,1.5,.08,'glass');for(const x of [-.45,0,.45]){box(f,'noren',x,y+2.38,1.20,.4,.65,.025,'green');face(f,'noren',x,y+2.38,1.221,.38,.6);}box(f,'lantern',1.7,y+2.3,1.05,.42,.7,.42,'glow','cylinder');face(f,'menu',-1.95,y+1.25,1.31,.62,.8);box(f,'crate',1.8,y+(.3+.15*variation)/2,.4,.6,.3+.15*variation,.5,'wood');box(f,'bin',1.85,y+.4,-.4,.5,.8,.5,'dark');box(f,'AC',-1.65,y+2.5,1.05,.8,.4,.35,'cream');box(f,'pipe',-2.15,y+1.4,1.12,.06,2.5,.06,'metal');}
 m.shops.push({id:f.id,type,point:f.point,polygon:f.polygon,heading,source:f.source,variation});}
 m.stats={platformFixtures:m.fixtures.filter(f=>f.platform).length,signs:m.faces.filter(f=>['station','departure','wayfinding','metro','bus','taxi','map','clock','kiosk','police'].includes(f.tile)).length,vending:m.fixtures.filter(f=>f.role==='platform-vending').length,benches:m.fixtures.filter(f=>f.role.endsWith('bench')).length,catenarySupports:m.catenary.length,wires:m.wires.length,droppers:m.instances.filter(i=>i.role==='dropper').length,railSignals:m.signals.length,rotaryProps:m.rotary.length,shelters:m.rotary.filter(r=>r.type.endsWith('shelter')).length,koban:m.rotary.filter(r=>r.type==='koban').length,info:m.rotary.filter(r=>r.type==='info').length,storefronts:m.shops.length,archetypes:Object.fromEntries(SHOP_TYPES.map(t=>[t,m.shops.filter(s=>s.type===t).length])),lanterns:m.instances.filter(i=>i.role==='lantern').length,noren:m.instances.filter(i=>i.role==='noren').length,menus:m.faces.filter(f=>f.tile==='menu').length,baselineMajor:m.baseline.major,baselineMinor:m.baseline.minor,newMajor:m.collisions.filter(c=>c.classification==='major').length,newMinor:m.collisions.filter(c=>c.classification==='minor').length,skippedCandidates:m.skipped.length,skippedReasons:Object.fromEntries([...new Set(m.skipped.flatMap(s=>s.issues))].map(r=>[r,m.skipped.filter(s=>s.issues.includes(r)).length])),modelBuildTimeMs:Math.round(performance.now()-started)};return m;
}

export function buildDetailModel(...args){return finishSteps(buildDetailModelSteps(...args));}
