import {Group,Mesh,MeshStandardMaterial,ShaderMaterial,Float32BufferAttribute,Color,AdditiveBlending} from 'three';
import {polygonGeometry,merge,triangleCount} from '../geo/geometry.mjs';
import {buildWetModel,NIGHT_PROFILES} from './model.mjs';
import {createNightBloom} from './bloom.mjs';
export function reflectionSourceWeight(x,z){const sources=[[-28,-23,20],[27,-19,18],[-25,25,16],[28,27,16],[-145,0,24],[-65,-55,24],[22,52,20],[2,-115,20]];return sources.reduce((v,[sx,sz,r])=>Math.max(v,Math.max(0,1-Math.hypot(x-sx,z-sz)/r)),0);}
function batch(records){const list=[],ends=[];let count=0;for(const r of records){for(const piece of r.pieces){const g=polygonGeometry(piece.polygon,piece.y),p=g.attributes.position,uv=[],colors=[],color=new Color(r.color),c=Math.cos(r.angle),s=Math.sin(r.angle);for(let i=0;i<p.count;i++){const x=p.getX(i)-r.center[0],z=p.getZ(i)-r.center[1];uv.push((c*x+s*z)/r.w*.5+.5,(-s*x+c*z)/r.l*.5+.5);const light=reflectionSourceWeight(p.getX(i),p.getZ(i));colors.push(color.r*light,color.g*light,color.b*light);}g.setAttribute('uv',new Float32BufferAttribute(uv,2));g.setAttribute('color',new Float32BufferAttribute(colors,3));list.push(g);count+=triangleCount(g)*3;}ends.push(count);}const g=merge(list);list.forEach(g=>g.dispose());return {geometry:g,ends};}
/** @param {any} data @param {{ground?:any,time?:any,environment?:any,renderer?:import('three').WebGLRenderer|null,tier?:string,model?:any}} options */
export function buildNightglow(data,{ground,time,environment,renderer=/** @type {import('three').WebGLRenderer|null} */ (null),tier='medium',model:preparedModel=null}={}){
 const model=preparedModel??buildWetModel(data,ground),root=new Group();root.name='s13-wet-night';const patches=batch(model.patches),reflections=batch(model.reflections);
 const wet=new MeshStandardMaterial({color:0x203443,roughness:.23,metalness:.16,transparent:true,opacity:.18,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1});
 const reflection=new ShaderMaterial({transparent:true,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2,polygonOffsetUnits:-2,blending:AdditiveBlending,uniforms:{strength:{value:1}},vertexShader:'attribute vec3 color;varying vec2 vUv;varying vec3 tint;void main(){vUv=uv;tint=color;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`uniform float strength;varying vec2 vUv;varying vec3 tint;void main(){vec2 d=abs(vUv-.5)*2.;float soft=max(0.,1.-max(d.x,d.y));float streak=.7+.3*sin(vUv.y*67.+vUv.x*13.);gl_FragColor=vec4(tint*.8,soft*soft*streak*.2*strength);
#include <tonemapping_fragment>
#include <colorspace_fragment>
}`});
 const patchMesh=new Mesh(patches.geometry,wet),reflectionMesh=new Mesh(reflections.geometry,reflection);patchMesh.name='s13-wet-patches';reflectionMesh.name='s13-selected-reflections';root.add(patchMesh,reflectionMesh);const bloom=renderer?createNightBloom(renderer):null;const stats={tier,patches:0,reflections:0,triangles:0,batches:2,extraBloomDrawCalls:0,geometries:2,addedLights:0};let disposed=false,postprocessEnabled=true,mirrorLevel=0;
 function refresh(){const p=NIGHT_PROFILES[stats.tier],active=time.isDark()&&environment.active;root.visible=active;environment.setNightglow(active?p.glow:0);stats.patches=Math.min(p.patches,model.patches.length);stats.reflections=Math.min(p.reflections,model.reflections.length);patches.geometry.setDrawRange(0,patches.ends[stats.patches-1]??0);reflections.geometry.setDrawRange(0,reflections.ends[stats.reflections-1]??0);stats.triangles=(patches.geometry.drawRange.count+reflections.geometry.drawRange.count)/3;stats.extraBloomDrawCalls=active&&postprocessEnabled&&p.bloom?2:0;stats.active=active;stats.bloomStrength=active&&postprocessEnabled?p.bloom:0;reflection.uniforms.strength.value=(.55+.45*p.glow)*(1-.6*mirrorLevel);}
 const off=time.subscribe(refresh);refresh();return {root,model,stats,bloom,refresh,setPostprocess(enabled){postprocessEnabled=enabled;refresh();},
  // RUN 12.2: while the real road mirror is up, the painted reflection patches step back so the two do not double.
  setMirror(level){const v=Math.max(0,Math.min(1,level||0));if(Math.abs(v-mirrorLevel)<.02)return;mirrorLevel=v;refresh();},setTier(t){if(!NIGHT_PROFILES[t])throw Error('Invalid night profile');stats.tier=t;refresh();},render(scene,camera){if(bloom)return bloom.render(scene,camera,stats.tier,stats.active&&postprocessEnabled);renderer?.render(scene,camera);},dispose(){if(disposed)return;disposed=true;off();environment.setNightglow(0);bloom?.dispose();patches.geometry.dispose();reflections.geometry.dispose();wet.dispose();reflection.dispose();root.removeFromParent();root.clear();}};
}
