import {readFileSync,writeFileSync} from 'node:fs';
const read=p=>JSON.parse(readFileSync(p)),r=read('evidence/s10/simulation.json'),profiles=read('evidence/s10/profiles.json'),render=read('evidence/s10/rendering.json'),s8=read('evidence/s8/geometry.json'),s9=read('evidence/s9/simulation.json');
const lines=['RUN S10 — Crowd / Life System','Base: f47b140fd8f3e9bb19b4d37403dd2a44b36f2cc3 (Visual QA version 4).','Current: revision containing this report; exact commit and published version are reported in delivery.','No subagents used. S11+ and GTA remain absent.','',`Pedestrian network: ${JSON.stringify(r.network)}`];
for(const tier of ['high','medium','low']){const p=profiles[tier],g=render[tier],b=s8.tiers[tier].sceneCPU,t=s9.rendering[tier];lines.push('',tier.toUpperCase(),`Initial total ${p.total}; archetypes ${JSON.stringify(p.archetypes)}`,`Modes ${JSON.stringify(p.modes)}; states ${JSON.stringify(p.states)}; groups ${p.groupCount}`,`Hachiko ${p.hachiko}; Center-gai ${p.centerGai}`,`Crowd: geometry ${g.geometries}, material ${g.materials}, batches ${g.batches}, triangles ${g.triangles}`,`Scene CPU sum: ${b.triangles+t.triangles+g.triangles} triangles / ${b.batches+t.batches+g.batches} mesh batches. GPU drawCalls unmeasured; S0 grid/axes and S1 diagnostics excluded.`);}
lines.push('','180-second HIGH simulation:',JSON.stringify(r.crowd,null,2),'','Scramble completed flow (forward / reverse):');
for(const [id,name] of [['way/355248078','west'],['way/355248080','north'],['way/355248081','east'],['way/355248083','south'],['way/754454449','diagonal']])lines.push(`${name} ${id}: ${r.crowd.completed[id+':1']??0} / ${r.crowd.completed[id+':-1']??0}`);
lines.push('',`Crowd/traffic audit: ${JSON.stringify(r.audit)}`,`Crowd CPU ms: ${JSON.stringify(r.crowdCPU)}`,`Traffic CPU ms in S10: ${JSON.stringify(r.trafficCPU)}; S9 saved reference ${JSON.stringify(s9.updateMs)}. Node timings vary with machine load; not browser FPS.`,`S9 after S10: route-end relocations ${r.traffic.routeFailures} (baseline 62), long-stop recoveries ${r.traffic.recoveries} (baseline 18). Vehicle red violations ${r.traffic.redViolations}.`,`Traffic actual crossing entries: ${JSON.stringify(r.traffic.crossingEntries)}`,'','Automated tests:');
for(const p of ['evidence/s10/tests.log','evidence/s10/regression.log'])lines.push(p,...readFileSync(p,'utf8').split('\n').filter(l=>/^[ℹ#] (tests|pass|fail|cancelled|skipped|duration_ms)/.test(l)));
lines.push('','Build: see build.txt.','Console / WebGL / HIGH FPS / actual GPU drawCalls: UNVERIFIED; connection timeout.','CAM-02/03/05/07 visuals and CAM-04/06 visual regression: UNVERIFIED. No screenshot is claimed.','S7 763 signage baseline, S8 369 HIGH fixtures, S2 67 crossings and prior modules verified by regression tests.','Visual QA: https://shibuya-scene-visual-qa.kesdemon.chatgpt.site (publication outcome and version in delivery).','','Known limits:',`- Conservative path cells reject narrow/ambiguous connections; rejected crossing paths ${r.network.rejectedCrossings}. No elevated walking or interiors.`,`- Crowd recoveries ${r.crowd.recoveries}; maximum simultaneous stopped actors/group separations: ${JSON.stringify(r.audit.minor)}. Local avoidance is approximate, not full crowd physics.`, '- Pedestrian crossing completion extends vehicle red beyond nominal phase when needed. Vehicle route logic is unchanged; traffic counts therefore differ from S9.', '- Body-envelope contact is audited separately from reserved exit capacity; reservation occupancy alone is not a physical overlap.', '- Arms/accessories use simplified silhouettes; animation and interpolation have no skeletal or rigid-body simulation.', '- Visual and performance acceptance still needs a browser with a functioning connection.','',readFileSync('evidence/s10/IMPLEMENTATION_NOTES.txt','utf8'),'STOP after S10.');
writeFileSync('evidence/s10/S10_REPORT.txt',lines.join('\n')+'\n');
