import {Group,Mesh,MeshStandardMaterial,BufferGeometry,Float32BufferAttribute,DataTexture,RGBAFormat,RepeatWrapping,SRGBColorSpace,HemisphereLight,DirectionalLight,DoubleSide,PlaneGeometry} from 'three';
import {polygonGeometry,merge,triangleCount} from '../geo/geometry.mjs';
import {seededRandom,distance,signedArea,cleanLine} from '../geo/core.mjs';
import {polygons,buildGroundModel,difference,intersection,union} from './model.mjs';
import {GROUND as C} from './config.mjs';
export function inspectGeometry(g){const p=g.attributes.position,idx=g.index;let nonFinite=0,badIndices=0,degenerate=0;const bounds={minX:Infinity,maxX:-Infinity,minY:Infinity,maxY:-Infinity,minZ:Infinity,maxZ:-Infinity};for(let i=0;i<p.count;i++){for(const [k,v] of [['X',p.getX(i)],['Y',p.getY(i)],['Z',p.getZ(i)]]){if(!Number.isFinite(v))nonFinite++;bounds['min'+k]=Math.min(bounds['min'+k],v);bounds['max'+k]=Math.max(bounds['max'+k],v);}}for(let i=0;i<(idx?.count??p.count);i+=3){const ids=[0,1,2].map(j=>idx?idx.getX(i+j):i+j);if(ids.some(j=>j<0||j>=p.count)){badIndices++;continue;}const v=ids.map(j=>[p.getX(j),p.getY(j),p.getZ(j)]),a=v[1].map((x,j)=>x-v[0][j]),b=v[2].map((x,j)=>x-v[0][j]);if(Math.hypot(a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0])<1e-8)degenerate++;}return {nonFinite,badIndices,degenerate,bounds};}
function geometry(m,height,subdivide=false,diagnostics){const list=[];for(const p of polygons(m)){p.outer=cleanLine(p.outer);p.holes=p.holes.map(cleanLine).filter(h=>h.length>=3&&Math.abs(signedArea(h))>1e-6);if(p.outer.length<3||Math.abs(signedArea(p.outer))<1e-6){diagnostics.discardedDegenerate++;continue;}let g;try{g=polygonGeometry(p);}catch(e){diagnostics.triangulationFailures++;throw e;}const raw=g.toNonIndexed(),a=raw.attributes.position,values=[];function triangle(v,depth=0){if(subdivide&&depth<12&&Math.max(...v.map((p,i)=>distance(p,v[(i+1)%3])))>2){const lengths=v.map((p,i)=>distance(p,v[(i+1)%3]));const i=lengths.indexOf(Math.max(...lengths)),a=v[i],b=v[(i+1)%3],c=v[(i+2)%3],mid=a.map((x,j)=>(x+b[j])/2);triangle([a,mid,c],depth+1);triangle([mid,b,c],depth+1);return;}const area=Math.abs((v[1][0]-v[0][0])*(v[2][1]-v[0][1])-(v[1][1]-v[0][1])*(v[2][0]-v[0][0]));if(area<1e-7){diagnostics.discardedDegenerate++;return;}for(const p of v)values.push(p[0],typeof height==='function'?height(p):height,p[1]);}for(let i=0;i<a.count;i+=3)triangle([0,1,2].map(j=>[a.getX(i+j),a.getZ(i+j)]));raw.dispose();g.dispose();if(!values.length)continue;g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(values,3));g.computeVertexNormals();list.push(g);}if(!list.length)return null;const result=merge(list);list.forEach(g=>g.dispose());return result;}
export function texture(kind){const size=256,rng=seededRandom('ground-'+kind),bytes=new Uint8Array(size*size*4);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const i=(y*size+x)*4;let v;if(kind==='asphalt'){v=55+(rng()-.5)*20+Math.sin(x*.07)*Math.sin(y*.045)*3;if(rng()<.025)v+=18;}else{const row=Math.floor(y/32),px=(x+(row%2)*32)%64;v=143+(rng()-.5)*10+Math.sin(Math.floor((x+(row%2)*32)/64)*17+row*11)*8;if(px<2||y%32<2)v-=32;else if(px<4||y%32<4)v+=7;}bytes.set([v*.98,v,v*1.02,255],i);}const t=new DataTexture(bytes,size,size,RGBAFormat);t.wrapS=t.wrapT=RepeatWrapping;t.colorSpace=SRGBColorSpace;t.needsUpdate=true;return t;}
export function createAsphaltMaterial(){const map=texture('asphalt');return new MeshStandardMaterial({map,bumpMap:map,bumpScale:.025,roughness:.96,metalness:0});}
export function buildGround(data,{model:preparedModel=null}={}){const started=performance.now(),model=preparedModel??buildGroundModel(data),root=new Group();root.name='s2-ground';const diagnostics={triangulationFailures:0,discardedDegenerate:0};const materials={asphalt:createAsphaltMaterial(),sidewalk:new MeshStandardMaterial({map:texture('sidewalk'),bumpMap:texture('sidewalk'),bumpScale:.055,roughness:.9,metalness:0}),curb:new MeshStandardMaterial({color:0xb5b4ae,roughness:.95,side:DoubleSide}),paint:new MeshStandardMaterial({color:0xf2efe4,roughness:.85}),tactile:new MeshStandardMaterial({color:0xecc12e,roughness:.9})};const batches={asphalt:[],sidewalk:[],curb:[],paint:[],tactile:[]};
 const add=(k,m,y,sub=false)=>{const g=geometry(m,y,sub,diagnostics);if(g)batches[k].push(g);};
 add('asphalt',model.roads,0);add('sidewalk',difference(model.flatSidewalk,model.curbTop),C.curb);add('sidewalk',difference(model.ramps,model.curbTop),model.height,true);add('curb',difference(model.curbTop,model.corridors),C.curb);add('curb',intersection(model.curbTop,model.corridors),model.height,true);
 const side=[];for(const ring of model.boundaries)for(let i=1;i<ring.length;i++){const a=ring[i-1],b=ring[i],steps=Math.max(1,Math.ceil(distance(a,b)));for(let s=0;s<steps;s++){const p=a.map((v,j)=>v+(b[j]-v)*s/steps),q=a.map((v,j)=>v+(b[j]-v)*(s+1)/steps),h=model.height(p),k=model.height(q);if(Math.max(h,k)<1e-6)continue;const v=[[p[0],0,p[1]],[q[0],0,q[1]],[q[0],k,q[1]],[p[0],h,p[1]]];if(k>1e-6)side.push(...v[0],...v[1],...v[2]);if(h>1e-6)side.push(...v[0],...v[2],...v[3]);}}
 if(side.length){const g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(side,3));g.computeVertexNormals();batches.curb.push(g);}
 add('paint',union(...model.crossings.flatMap(c=>c.stripes.map(s=>s.polygon)),...model.stopLines,...model.guides,...model.arrows),C.paintY);add('tactile',union(...model.tactiles),p=>model.height(p)+C.paintY,true);
 const checks={},tris={};for(const [name,gs] of Object.entries(batches)){if(!gs.length)continue;const g=merge(gs);gs.forEach(g=>g.dispose());const uv=[];const p=g.attributes.position;for(let i=0;i<p.count;i++)uv.push(p.getX(i)/4,p.getZ(i)/4);g.setAttribute('uv',new Float32BufferAttribute(uv,2));checks[name]=inspectGeometry(g);tris[name]=triangleCount(g);const mesh=new Mesh(g,materials[name]);mesh.name='ground-'+name;root.add(mesh);}
 // Land beneath mapped roads/sidewalks: uncovered parcels must not reveal the sky dome.
 const landGeometry=new PlaneGeometry(C.limit*2,C.limit*2);landGeometry.rotateX(-Math.PI/2);landGeometry.translate(0,-.08,0);
 const landUV=landGeometry.attributes.uv;for(let i=0;i<landUV.count;i++)landUV.setXY(i,landUV.getX(i)*C.limit/2,landUV.getY(i)*C.limit/2);
 materials.land=new MeshStandardMaterial({map:texture('sidewalk'),color:0x777b80,roughness:.96,metalness:0});
 const land=new Mesh(landGeometry,materials.land);land.name='ground-land';land.receiveShadow=true;root.add(land);tris.land=2;checks.land=inspectGeometry(landGeometry);
 // Fixed inspection daylight, owned by Ground; no environment/night implementation.
 const hemi=new HemisphereLight(0xf0f5ff,0x73706a,2),sun=new DirectionalLight(0xfff6e9,2.2);sun.position.set(-80,180,90);root.add(hemi,sun);
 const stats={...model.stats,roadTris:tris.asphalt??0,sidewalkTris:tris.sidewalk??0,curbTris:tris.curb??0,totalGroundTris:Object.values(tris).reduce((s,n)=>s+n,0),approximateDrawCalls:Object.keys(tris).length,buildTimeMs:Math.round(performance.now()-started),...diagnostics,checks};
 return {root,model,stats,dispose(){root.removeFromParent();for(const o of [...root.children]){o.geometry?.dispose();root.remove(o);}for(const m of Object.values(materials)){for(const t of new Set([m.map,m.bumpMap]))t?.dispose();m.dispose();}}};
}
