import {finishStepsAsync} from '../quality/runtime.mjs';
import {Group,Mesh,MeshStandardMaterial,BoxGeometry,HemisphereLight,BufferGeometry,Float32BufferAttribute,Vector3,Quaternion,Euler,Box3} from 'three';
import {extrude,merge,triangleCount,InstancedBuilder} from '../geo/geometry.mjs';
import {sample,length,offset} from '../geo/core.mjs';
import {inspectGeometry} from '../ground/render.mjs';
import {union,polygons} from '../ground/model.mjs';
import {multi} from '../buildings/model.mjs';
import {buildStationModel,buildStationModelSteps} from './model.mjs';
const COLORS={stationConcrete:0xb2b5b2,concreteDark:0x6b7475,steel:0x9ba6aa,darkSteel:0x35454e,railMetal:0x858d93,ballast:0x5d625c,platform:0xbcbcb1,tactile:0xeac538,canopy:0xe3e8e5,glass:0x7997a2,greenBand:0x198447};
export function buildStation(data,options={}){const started=performance.now(),model=options.model??buildStationModel(data,options),root=new Group();root.name='s5-station-core';const materials=Object.fromEntries(Object.entries(COLORS).map(([k,color])=>[k,new MeshStandardMaterial({color,roughness:k==='railMetal'?.4:.85,metalness:k==='railMetal'?.5:0})]));const geometry=new BoxGeometry(1,1,1),statics={},meshes=[],builders=[],batches={},checks={};
 let discardedDegenerate=0;
 function collect(channel,g){const src=g.index?g.toNonIndexed():g,p=src.attributes.position,positions=[],normals=[],n=src.attributes.normal;for(let i=0;i<p.count;i+=3){const a=new Vector3().fromBufferAttribute(p,i),b=new Vector3().fromBufferAttribute(p,i+1),c=new Vector3().fromBufferAttribute(p,i+2);if(b.sub(a).cross(c.sub(a)).length()<1e-8){discardedDegenerate++;continue;}for(let j=i;j<i+3;j++){positions.push(p.getX(j),p.getY(j),p.getZ(j));normals.push(n.getX(j),n.getY(j),n.getZ(j));}}const clean=new BufferGeometry();clean.setAttribute('position',new Float32BufferAttribute(positions,3));clean.setAttribute('normal',new Float32BufferAttribute(normals,3));if(src!==g)src.dispose();g.dispose();if(positions.length)(statics[channel]??=[]).push(clean);else clean.dispose();}
 const joinedDecks=model.masses.filter(m=>m.role==='pedestrian-deck');
 for(const m of model.masses)if(m.role!=='pedestrian-deck')collect(m.material,extrude(m.polygon,m.top-m.bottom,m.bottom));
 if(joinedDecks.length){const m=joinedDecks[0];for(const p of polygons(union(...joinedDecks.map(x=>multi(x.polygon)))))collect(m.material,extrude(p,m.top-m.bottom,m.bottom));}
 const canopy=model.ginzaCanopy;
 if(canopy){
  const lines=canopy.profile.map(([u])=>offset(canopy.centerline,-u));
  for(let j=0;j<canopy.profile.length-1;j++){const vertices=[],indices=[];for(let i=0;i<canopy.centerline.length;i++){vertices.push(lines[j][i][0],canopy.base+canopy.profile[j][1],lines[j][i][1],lines[j+1][i][0],canopy.base+canopy.profile[j+1][1],lines[j+1][i][1]);if(i){const q=(i-1)*2;indices.push(q,q+1,q+2,q+1,q+3,q+2);}}
  const g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(vertices,3));g.setIndex(indices);g.computeVertexNormals();collect('canopy',g);}
  for(const r of canopy.portalEnds)for(let i=0;i<canopy.profile.length-1;i++){const points=canopy.profile.slice(i,i+2).map(([u,h])=>new Vector3(r.point[0]+Math.cos(r.heading)*u,canopy.base+h,r.point[1]-Math.sin(r.heading)*u)),v=points[1].clone().sub(points[0]),mid=points[0].clone().add(points[1]).multiplyScalar(.5),q=new Quaternion().setFromUnitVectors(new Vector3(0,0,1),v.clone().normalize()),e=new Euler().setFromQuaternion(q);model.instances.push({role:'ginza-canopy-rib',position:mid.toArray(),scale:[.12,.16,v.length()],heading:0,rotation:[e.x,e.y,e.z],material:'steel'});}
 }
 for(const r of model.instances){if(r.from){const from=new Vector3(...r.from),to=new Vector3(...r.to),v=to.clone().sub(from),q=new Quaternion().setFromUnitVectors(new Vector3(0,0,1),v.clone().normalize()),e=new Euler().setFromQuaternion(q);r.position=from.add(to).multiplyScalar(.5).toArray();r.scale=[r.thickness,r.thickness,v.length()];r.heading=0;r.rotation=[e.x,e.y,e.z];}}
 for(const [channel,list] of Object.entries(statics)){const g=merge(list);list.forEach(g=>g.dispose());const mesh=new Mesh(g,materials[channel]);mesh.name='station-'+channel;root.add(mesh);meshes.push(mesh);checks[channel]=inspectGeometry(g);batches[channel]={type:'merged',triangles:triangleCount(g)};}
 for(const [channel,material] of Object.entries(materials)){const records=model.instances.filter(r=>r.material===channel);if(!records.length)continue;const b=new InstancedBuilder(geometry,material,records.length);for(const r of records)b.add(...r.position,r.heading,r.scale,0xffffff,r.rotation??null);const mesh=b.build();mesh.name='station-repeat-'+channel;root.add(mesh);builders.push(b);batches['repeat-'+channel]={type:'instanced',instances:records.length,triangles:12*records.length};}
 const light=new HemisphereLight(0xeaf2ff,0x686b65,1);light.name='station-inspection-light';root.add(light);root.updateMatrixWorld(true);const b=new Box3().setFromObject(root);
 const count=role=>model.masses.filter(m=>m.role===role).length,icount=role=>model.instances.filter(i=>i.role===role).length;
 const stats={sourceRails:model.audit.counts,alignmentCount:model.alignments.length,JRLength:model.alignments.filter(a=>a.family==='JR').reduce((s,a)=>s+a.length,0),GinzaLength:model.alignments.filter(a=>a.family==='Ginza').reduce((s,a)=>s+a.length,0),deckCount:model.decks.length,deckPolygons:count('jr-deck')+count('ginza-deck'),girderCount:count('jr-girder')+count('ginza-girder'),pierCount:icount('pier'),supportCount:model.supports.length,rejectedSupportCount:model.supportRejected.length,railCount:model.railPairs.length*2,sleeperInstances:icount('sleeper'),platformCount:model.platforms.length,tactileCount:count('platform-tactile'),roofCount:count('platform-roof'),postCount:icount('platform-post'),hachikoGenerated:!!model.hachiko,ginzaGenerated:!!model.ginzaCanopy,pedestrianDeckCount:model.pedestrians.filter(d=>!d.stair).length,pedestrianStairCount:model.pedestrians.filter(d=>d.stair).length,pedestrianLength:model.pedestrians.reduce((s,d)=>s+d.length,0),reservationsUsed:model.reservations.filter(r=>r.status==='used').length,reservationsUntouched:model.reservations.filter(r=>r.status==='untouched').length,majorPenetrations:model.penetrations.filter(p=>p.classification==='major').length,minorPenetrations:model.penetrations.filter(p=>p.classification==='minor').length,expectedInterfaces:model.penetrations.filter(p=>p.classification==='expected').length,invalid:model.audit.invalid,duplicateSegments:model.audit.duplicateSegments.length,skipped:model.skipped,stationTriangles:Object.values(batches).reduce((s,b)=>s+b.triangles,0),materials:Object.keys(materials).length,mergedBatches:meshes.length,instancedBatches:builders.length,approximateDrawCalls:Object.keys(batches).length,instances:model.instances.length,geometries:meshes.length+1,textures:0,discardedDegenerate,buildTimeMs:Math.round(performance.now()-started),bounds:{min:b.min.toArray(),max:b.max.toArray()},checks,batches};
 let disposed=false;return {root,model,stats,dispose(){if(disposed)return;disposed=true;root.removeFromParent();builders.forEach(b=>b.dispose());meshes.forEach(m=>m.geometry.dispose());geometry.dispose();Object.values(materials).forEach(m=>m.dispose());root.clear();}};
}

const timingStats=values=>{const sorted=[...values].sort((a,b)=>a-b),n=sorted.length,p=q=>n?sorted[Math.min(n-1,Math.ceil(q*n)-1)]:0,total=values.reduce((s,v)=>s+v,0);return {total,average:n?total/n:0,median:n?(sorted[Math.floor((n-1)/2)]+sorted[Math.floor(n/2)])/2:0,p95:p(.95),max:n?sorted[n-1]:0};};
async function finishStationStepsTimed(steps,trace){let item,last=null;try{while(true){const nextStart=performance.now();if(last)last.nextStartAfterWait=nextStart;item=steps.next();const nextEnd=performance.now(),record={index:trace.yields.length,nextStart,nextEnd,computeMs:nextEnd-nextStart,waitStart:null,rafAt:null,timeoutAt:null,nextStartAfterWait:null};trace.yields.push(record);if(item.done)break;record.waitStart=performance.now();await new Promise(resolve=>requestAnimationFrame(()=>{record.rafAt=performance.now();setTimeout(()=>{record.timeoutAt=performance.now();resolve();},0);}));last=record;}return item.value;}finally{steps.return?.();}}
function finalizeTiming(trace){const yielded=trace.yields.filter(r=>r.waitStart!==null),compute=trace.yields.map(r=>r.computeMs),raf=yielded.map(r=>r.rafAt-r.waitStart),timer=yielded.map(r=>r.timeoutAt-r.rafAt),gap=yielded.map(r=>r.nextStartAfterWait-r.timeoutAt);trace.generatorEnd=trace.yields.at(-1)?.nextEnd??performance.now();trace.summary={yieldCount:yielded.length,compute:timingStats(compute),rafWait:timingStats(raf),timeoutWait:timingStats(timer),otherGap:timingStats(gap)};return trace;}
export async function buildStationAsync(data,options={}){const trace=options.timingTrace,timing=options.stageTiming;if(!trace){const model=options.model??await finishStepsAsync(buildStationModelSteps(data,options),undefined,timing),started=timing&&performance.now(),result=buildStation(data,{...options,model});if(timing)timing.computeMs=(timing.computeMs??0)+(performance.now()-started);return result;}trace.consumerStart=performance.now();trace.yields=[];trace.markStationModelStart=t=>{trace.stationModelStart=t;};const steps=buildStationModelSteps(data,options);trace.stepsCreated=performance.now();const model=options.model??await finishStationStepsTimed(steps,trace);trace.modelReady=performance.now();trace.renderStart=performance.now();const result=buildStation(data,{...options,model});trace.renderEnd=performance.now();finalizeTiming(trace);if(timing){timing.computeMs=(timing.computeMs??0)+trace.summary.compute.total+(trace.renderEnd-trace.renderStart);timing.cooperativeWaitMs=(timing.cooperativeWaitMs??0)+trace.summary.rafWait.total+trace.summary.timeoutWait.total+trace.summary.otherGap.total;timing.yieldCount=(timing.yieldCount??0)+trace.summary.yieldCount;}return result;}
